import { Db } from './casaDoCodigo-db'
import { Injectable } from '@angular/core'

@Injectable ({
    providedIn: 'root'
})

export class DbService {
    retriveAll(): Db[] {
        return DbLivros
    }
}

let DbLivros: Db[] = [
    {
        id: 1,
        title: 'html5 e css3',
        upon: 'Domine a web do futuro',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 228,
        datePubli: '05/2012',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'Crie páginas elegantes de forma simples! HTML e CSS, quando bem utilizados, podem ser o sucesso de um projeto e, com os novos recursos, muito do que antes era trabalhoso agora não é mais. Aprenda as melhores técnicas para escrever seu site por meio de exemplos práticos de funcionalidades úteis do cotidiano. Construa menus, aplique efeitos, estilize elementos visuais, melhore a semântica da sua página e muito mais!',
        writer: 'Natan Souza',
        aboutWriter: 'Lucas Mazza faz parte da equipe de desenvolvedores da Plataformatec, empresa de desenvolvimento de São Paulo, especializada em Ruby on Rails. Combinando a linguagem Ruby com HTML, CSS e JavaScript, ele busca desenvolver interfaces elegantes aliado a um código de qualidade, que satisfaça usuários e desenvolvedores envolvidos. No seu tempo livre, ele é aficionado por filmes, música, tecnologia e contribui com projetos open Sousce no GitHub. Seu usuário no GitHub é lucasmazza e está no Twitter em @lucasmazza.',
        writerImg: 'assets/image/writers/lucas-mazza.png',
        bigImageUrl: 'assets/image/books/HTML5eCSS3.png',
        middleImageUrl: 'assets/image/books/HTML5eCSS3.png',
        smallImageUrl: 'assets/image/books/HTML5eCSS3.png'
    }, 
    {
        id: 2,
        title: 'css3 eficiente',
        upon: 'Técnicas e ferramentas que fazem a diferença nos seus estilos',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 144,
        datePubli: '06/2015',
        pricePrinted: 52.15,
        priceEbook: 23.92,
        pricePackage: 62.99,
        description: 'Quando aprendemos a trabalhar com CSS, frequentemente nos pegamos perdidos em detalhes fundamentais que não nos são explicados. Por vezes, alguns desses detalhes passam despercebidos até pelo desenvolvedor front-end mais experiente. Mas como ir além do conhecimento básico do CSS e preparar o caminho para explorar tópicos mais avançados?',
        writer: 'Tárcio Zemel',
        aboutWriter: 'Tárcio Zemel trabalha com desenvolvimento web há 15 anos e atuar nessa área é uma das coisas que mais gosta de fazer. É sócio-fundador da empresa webfatorial, na qual trabalha em projetos web para grandes marcas do mundo todo.',
        bigImageUrl: 'assets/image/books/CSS3Eficiente.png',
        writerImg: 'assets/image/writers/tarcio-zemel.png',
        middleImageUrl: 'assets/image/books/CSS3Eficiente.png',
        smallImageUrl: 'assets/image/books/CSS3Eficiente.png'
    },
    {
        id: 3,
        title: 'sass',
        upon: 'Aprendendo pré-processadores CSS',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 166,
        datePubli: '08/2016',
        pricePrinted: 47.92,
        priceEbook: 29.95,
        pricePackage: 59.92,
        description: 'Na última década, surgiram os chamados processadores CSS, tecnologias que buscavam suprir as deficiências que encontrávamos na utilização de CSS comum, como repetição de código, ausência de funções, a difícil manutenção entre outros fatores. Sabemos que a única linguagem de estilos que os navegadores compreendem atualmente é o bom e velho CSS, daí a necessidade de um pré-processador que receba dados de entrada e os devolva compilados em um arquivo .css, facilitando o dia a dia do desenvolvimento front-end e trazendo grandes vantagens na implementação dos estilos.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Sass.png',
        middleImageUrl: 'assets/image/books/Sass.png',
        smallImageUrl: 'assets/image/books/Sass.png'
    },
    {
        id: 4,
        title: 'bootstrap 4',
        upon: 'Conheça a biblioteca front-end mais utilizada no mundo',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 172,
        datePubli: '05/2018',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'Fazer um site elegante nunca foi tão fácil, mesmo para quem não sabe escrever uma linha de CSS e, muito menos, entende como harmonizar cores, balancear elementos e tipografia. O Bootstrap é, resumidamente, um grande arquivo CSS com uma excelente documentação, que possui dezenas e dezenas de componentes prontos. No começo, foi criado pelo Twitter para servir como um guia de estilos em CSS da empresa; hoje, é a biblioteca mais famosa e utilizada no mundo.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Bootstrap.png',
        middleImageUrl: 'assets/image/books/Bootstrap.png',
        smallImageUrl: 'assets/image/books/Bootstrap.png'
    },
    {
        id: 5,
        title: 'ecmascript 6',
        upon: 'Entre de cabeça no futuro do JavaScript',
        about: 'Javascript',
        section: 'front-end',
        numPages: 227,
        datePubli: '05/2018',
        pricePrinted: 55.92,
        priceEbook: 35.55,
        pricePackage: 67.92,
        description: 'Nos últimos anos, a linguagem JavaScript cresceu bastante na comunidade de desenvolvedores, tornando-se mais robusta, poderosa e sendo usada em uma infinidade de aplicações de alto nível, tanto no front-end quanto no back-end das aplicações. Ela é a tecnologia por trás de ferramentas, frameworks e bibliotecas consagradas no mercado, tais como: Angular, Ember, React, Backbone, jQuery, Grunt. A lista é enorme. Atualmente, é essencial que um profissional de TI tenha domínio desta tecnologia, tanto para aplicações web, aplicativos mobile e/ou desktop. É exatamente para isto que este livro foi escrito. Para que você seja capaz de entender todas as mudanças que vieram com o ECMAScript 6, aprimorar suas habilidades como desenvolvedor e se destacar no mercado de trabalho que hoje é tão concorrido.',
        writer: 'Diego Martins de Pinho',
        aboutWriter: 'Bacharel em Ciência da Computação pela PUC-SP e MBA em Gestão da Tecnologia da Informação pela FIAP. É aficionado não somente por tecnologia, mas também por empreendedorismo e gestão de negócios. Trabalha com desenvolvimento web desde 2013 e sempre busca tempo para continuar aprendendo e para disseminar o conhecimento.',
        writerImg: 'assets/image/writers/diego-martins.png',
        bigImageUrl: 'assets/image/books/ECMAScript6.png',
        middleImageUrl: 'assets/image/books/ECMAScript6.png',
        smallImageUrl: 'assets/image/books/ECMAScript6.png'
    },
    {
        id: 6,
        title: 'angular 11 e firebase',
        upon: 'Construindo uma aplicação integrada com a plataforma do Google',
        about: 'Javascript',
        section: 'front-end',
        numPages: 163,
        datePubli: '03/2021',
        pricePrinted: 47.92,
        priceEbook: 33.55,
        pricePackage: 60.55,
        description: 'No desenvolvimento de aplicações web e mobile, há disponível uma quantidade expressiva de linguagens, frameworks e ferramentas. Nessa imensidão, é comum se questionar ou até ter inseguranças sobre qual o melhor caminho para a construção neste segmento. O Angular é uma plataforma que facilita a construção de aplicativos, combinando templates, injeção de dependências, tudo integrado às melhores práticas de desenvolvimento.',
        writer: 'Kheronn Khennedy Machado',
        aboutWriter: 'Kheronn Khennedy Machado é professor da rede pública estadual do Paraná. Atua na formação de professores para uso de tecnologia em sala de aula. Desenvolve desde 2007 aplicações para web e mobile, tendo recentemente focado em soluções que utilizam Javascript. Possui Mestrado em Informática pela UFPR e Graduação em Processamento de Dados pela Fatec Ourinhos.',
        writerImg: 'assets/image/writers/kheronn-khennedy.png',
        bigImageUrl: 'assets/image/books/AngularEFirebase.png',
        middleImageUrl: 'assets/image/books/AngularEFirebase.png',
        smallImageUrl: 'assets/image/books/AngularEFirebase.png'
    },
    {
        id: 7,
        title: 'guia prático de typescript',
        upon: 'Melhore suas aplicações JavaScript',
        about: 'Javascript',
        section: 'front-end',
        numPages: 178,
        datePubli: '07/2021',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.84,
        description: 'Desenvolvido e mantido pela Microsoft, o TypeScript é um pré-processador open source de códigos JavaScript que auxilia na escrita de códigos, desde os mais simples até os mais complexos, utilizando tipagem de dados e os princípios da Orientação a Objetos para o desenvolvimento de aplicações front-end, back-end e mobile.',
        writer: 'Thiago da Silva Adriano',
        aboutWriter: 'Thiago da Silva Adriano é Microsoft (MVP) e atualmente trabalha como Engenheiro de Software. Nesses últimos anos, focou nas tecnologias criadas pela Microsoft, mas sempre esteve antenado para as novas tecnologias que estão surgindo no mercado. Em um breve resumo, é uma pessoa apaixonada pelo que faz, tem a sua profissão como hobby.',
        writerImg: 'assets/image/writers/thiago-silva.png',
        bigImageUrl: 'assets/image/books/GuiaTypescript.png',
        middleImageUrl: 'assets/image/books/GuiaTypescript.png',
        smallImageUrl: 'assets/image/books/GuiaTypescript.png'
    },
    {
        id: 8,
        title: 'vue.js',
        upon: 'construa aplicações incríveis',
        about: 'Javascript',
        section: 'front-end',
        numPages: 174,
        datePubli: '04/2017',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'O modo como desenvolvemos código front-end mudou muito ao longo dos últimos anos. Mais do que dar as ferramentas necessárias para desenvolver, os frameworks de componentes reativos para interfaces web modernas vieram nos ajudar com padrões e reaproveitamento de código. Vue.js, ou simplesmente Vue, é uma biblioteca moderna de desenvolvimento front-end, uma lib JavaScript para componentes reativos para web. Ele ganhou muita visibilidade no mercado após ser adotado como padrão pelo Laravel, tendo a possibilidade de ser utilizado em qualquer projeto que possua front-end, independente da linguagem de programação escolhida.',
        writer: 'Caio Incau',
        aboutWriter: 'Caio Incau estudou Sistemas de Informação e trabalha com desenvolvimento de software na Caelum desde seus 18 anos. Durante sua estadia no mercado de TI, teve a oportunidade de trabalhar com Java, Ruby, JavaScript e Objective-C.',
        writerImg: 'assets/image/writers/caio-incau.png',
        bigImageUrl: 'assets/image/books/VueJS.png',
        middleImageUrl: 'assets/image/books/VueJS.png',
        smallImageUrl: 'assets/image/books/VueJS.png'
    },
    {
        id: 9,
        title: 'acessibilidade na web',
        upon: 'Boas práticas para construir sites e aplicações acessíveis',
        about: 'Outros',
        section: 'front-end',
        numPages: 246,
        datePubli: '04/2020',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 71.92,
        description: 'Acessibilidade na Web consiste na eliminação de barreiras de acesso em páginas e aplicações digitais para que pessoas com deficiência tenham autonomia na rede. Na verdade, acessibilidade na web beneficia todas as pessoas. Em algum momento da vida todos podem precisar de acessibilidade, seja devido a uma limitação temporária ou permanente. Quando não levamos em consideração o acesso de pessoas com deficiência, estamos tirando o direito de uma pessoa de navegar, interagir ou consumir produtos e serviços na rede. Empatia é o fator principal para que as aplicações que desenvolvemos sejam inclusivas.',
        writer: 'Reinaldo Ferraz',
        aboutWriter: 'Formado em desenho e computação gráfica e pós-graduado em design de hipermídia pela Universidade Anhembi Morumbi em São Paulo. Trabalha com desenvolvimento web desde 1998. Coordena as iniciativas de acessibilidade na Web do NIC.br e projetos relacionados a Open Web Platform, Digital Publishing e Web das Coisas. Representante do NIC.br em grupos de trabalho do W3C internacional em Acessibilidade na Web, Digital Publishing e Web das Coisas. Apaixonado por acessibilidade, usabilidade, padrões web, HTML, CSS e café sem açúcar.',
        writerImg: 'assets/image/writers/reinaldo-ferraz.png',
        bigImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        middleImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        smallImageUrl: 'assets/image/books/Acessibilidade-na-Web.png'
    },
    {
        id: 10,
        title: 'progressive web apps',
        upon: 'Construa aplicações progressivas com React',
        about: 'Outros',
        section: 'front-end',
        numPages: 443,
        datePubli: '04/2018',
        pricePrinted: 71.92,
        priceEbook: 31.92,
        pricePackage: 83.92,
        description: 'PWA é um acrônimo para Progressive Web Apps, ou Aplicações Web Progressivas. Com o passar dos dias, mais e mais sistemas mobile e navegadores suportam os requisitos PWA, com uma expectativa real de que a Progressive Enhancement, ou melhoria progressiva, deixe de apenas pertencer às boas práticas de desenvolvimento web e passe a ser norma. Desenvolver com melhoria progressiva é um paradigma em que a aplicação deverá estar disponível para todos, sejam usuários de microcomputadores ou smartphones, com browsers atualizados ou obsoletos, com conexão à internet ou não, propiciando uma experiência de acesso contínuo sem nenhum tipo de restrição tecnológica.',
        writer: 'Guilherme Pontes',
        aboutWriter: 'Um profissional de TI, que adora TI, principalmente quando se trata de minúcias relacionadas a Linux, Node.JS, Python, MySQL, MongoDB, apps mobile ou progressivas, e muito JavaScript. http://lgapontes.com/',
        writerImg: 'assets/image/writers/guilherme-pontes.png',
        bigImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        middleImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        smallImageUrl: 'assets/image/books/ProgressiveWebApps.png'
    },
    {
        id: 11,
        title: 'introdução à web semântica',
        upon: 'A inteligência da informação',
        about: 'Outros',
        section: 'front-end',
        numPages: 170,
        datePubli: '09/2012',
        pricePrinted: 47.92,
        priceEbook: 23.92,
        pricePackage: 59.92,
        description: 'Por que precisamos da Web Semântica? A Web de hoje não é suficiente? Estamos caminhando para uma Web com dados cada vez mais relacionados e abertos. A Web Semântica é uma extensão da nossa web atual, em que nós não vamos apenas ler e produzir conteúdo, mas usar as máquinas para relacionar e reutilizar essas informações da melhor maneira possível. Ela se baseia na ideia de que o conteúdo deve ter uma descrição digital, padronizada por vocabulários, que provê meios para as máquinas entenderem do que aquilo se trata, de modo que os computadores possam interpretar, gerar e distribuir conteúdo útil, de acordo com as necessidades dos usuários.',
        writer: 'Diego Eis',
        aboutWriter: 'Diego Eis é apaixonado e sempre trabalhou com internet. Em 2003, fundou o Tableless, onde escreve com vários outros autores sobre desenvolvimento web e front-end. Já palestrou em vários eventos nacionais de tecnologia, faculdades e empresas por todo o país, passou seis anos de sua carreira profissional dirigindo a própria empresa, fazendo projetos para companhias como Globo.com, Itaú, Nokia, Samsung e outras. É autor do livro Guia Front-End, destinado aos iniciantes da área. Atualmente, é gestor de produtos na Easynvest.',
        writerImg: 'assets/image/writers/diego-eis.png',
        bigImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        middleImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        smallImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png'
    },
    {
        id: 12,
        title: 'aprofundando em flutter',
        upon: 'Desenvolva aplicações Dart com Widgets',
        about: 'Outros',
        section: 'front-end',
        numPages: 319,
        datePubli: '06/2021',
        pricePrinted: 63.92,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'Flutter é um framework do Google que tem conquistado o coração de muitas pessoas no desenvolvimento de aplicativos cross-platform, tanto para dispositivos móveis, como com versões estáveis para desenvolvimento web, desktop e PWA. Sua estrutura baseada em widgets, que são componentes visuais ou não, com propriedades e eventos customizáveis através da linguagem Dart, abre um leque infinito de possibilidades para criar aplicações completas. Se você já conhece Flutter e quer dar o próximo passo nessa relação, este é o caminho.',
        writer: 'Everton Coimbra de Araújo',
        aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
        writerImg: 'assets/image/writers/everton-coimbra-de-araujo.png',
        bigImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        middleImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        smallImageUrl: 'assets/image/books/Aprofundandoemflutter.png'
    },
    {
        id: 13,
        title: 'lógica de programação com portugol',
        upon: 'Mais de 80 exemplos, 55 exercícios com gabarito e vídeos complementares',
        about: 'Lógica',
        section: 'programacao',
        numPages: 275,
        datePubli: '02/2022',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'O primeiro passo no mundo do desenvolvimento de aplicativos, softwares e sistemas informatizados envolve lógica de programação. É conhecer conceitos fundamentais sobre o funcionamento de comandos para passarmos para o computador o que ele deve fazer e qual a sequência correta do que deve ser feito. Isso se torna mais palpável com uma linguagem mais próxima à que já dominamos: o português. Com foco no aprendizado, Portugol é uma pseudo-linguagem de programação que oferece uma abordagem acessível para você aprender a montar seus primeiros algoritmos com lógica de programação.',
        writer: 'Joice Barbosa Mendes',
        aboutWriter: 'Joice Barbosa Mendes Bacharelada em Ciência da Computação (UNIFEI-MG) em 2009. Concluiu o Mestrado em Ciência e Tecnologia da Computação (UNIFEI-MG) em 2012, com foco em Sistemas Tutores Inteligentes. Possui Formação Pedagógica para Educação Profissional de Nível Médio (IFSP-SP). Iniciou sua carreira como docente em 2012, atuando em disciplinas de programação do ensino superior para cursos de engenharia e Sistemas de Informação. Em 2016 passou a atuar em disciplinas de lógica de programação e orientação a objetos no IFSP, para cursos técnicos e de graduação.',
        writerImg: 'assets/image/writers/joice-barbosa.png',
        bigImageUrl: 'assets/image/books/logica-programacao.png',
        middleImageUrl: 'assets/image/books/logica-programacao.png',
        smallImageUrl: 'assets/image/books/logica-programacao.png'
    },
    {
        id: 14,
        title: 'app inventor',
        upon: 'Seus primeiros aplicativos Android',
        about: 'Lógica',
        section: 'programacao',
        numPages: 305,
        datePubli: '11/2021',
        pricePrinted: 63.91,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'O App Inventor 2 é uma ferramenta inovadora, desenvolvida pelo Google e mantida hoje pelo Instituto de Tecnologia de Massachusetts (MIT). Com ela, é possível criar aplicativos para dispositivos móveis Android, por meio de uma linguagem visual, sem precisar decorar ou escrever códigos de linguagem de programação. Com um simples arrastar e inserir blocos para a área de programação, em uma interface intuitiva, é uma excelente ferramenta de aprendizado que permite que os recém-chegados à programação de computador criem aplicativos completos.',
        writer: 'Nelson Fabbri Gerbelli',
        aboutWriter: 'Nelson Fabbri Gerbelli é Tecnólogo em Processamento de Dados pela faculdade FAINAM, pós-graduado em Análise de Sistemas pela faculdade ESAN. Pedagogo e possui licenciatura plena em Informática. É professor em cursos de TI no Centro Estadual de Educação Tecnológica Paula Souza do Estado de São Paulo nas ETECs, atuando principalmente nas seguintes disciplinas: Tecnologia para mobilidade, técnicas de programação para internet e desenvolvimento de softwares com o Visual Studio.Net.',
        writerImg: 'assets/image/writers/nelson-fabbri.png',
        bigImageUrl: 'assets/image/books/AppInventor.png',
        middleImageUrl: 'assets/image/books/AppInventor.png',
        smallImageUrl: 'assets/image/books/AppInventor.png'
    },
    {
        id: 15,
        title: 'introdução à programação em c',
        upon: 'Os primeiros passos de um desenvolvedor',
        about: 'Lógica',
        section: 'programacao',
        numPages: 290,
        datePubli: '08/2015',
        pricePrinted: 63.92,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'Você já programou alguma vez na vida? Pois então, prepare-se: sua vida vai mudar. Ensinar a máquina a fazer o que quer que ela faça é extremamente divertido. C é uma ótima linguagem para quem quer aprender programação: é bastante popular, poderosa, e nos dá diferentes níveis de abstração.',
        writer: 'Mauricio Aniche',
        aboutWriter: 'Maurício é instrutor e desenvolvedor da Caelum, possui mais de 9 anos de experiência de desenvolvimento de softwares, tendo participado de projetos para grandes empresas nacionais e internacionais. Mauricio é também mestre em Ciência da Computação pela Universidade de São Paulo (USP) onde pesquisa sobre TDD e sua influência no design de sistemas orientados a objetos. Atualmente é aluno de doutorado pelo mesmo instituto. Palestrante em eventos nacionais e internacionais, com destaque para sua apresentação no 1o Workshop Internacional sobre Test-Driven Development, localizado em Paris, no ano de 2010, Agile Brazil 2010, 2011 e 2012, e QCON SP 2010 e 2012. Mauricio gosta de discutir sobre TDD, melhores práticas e princípios de orientação a objetos, métodos ágeis de desenvolvimento de software e linguagens de programação. Está no Twitter como @mauricioaniche .',
        writerImg: 'assets/image/writers/mauricio-aniche.png',
        bigImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png',
        middleImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png',
        smallImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png'
    },
    {
        id: 16,
	    title: 'lógica de programação',
	    upon: 'Crie seus primeiros programas usando Javascript e HTML',
	    about: 'Lógica',
	    section: 'programacao',
	    numPages: 180,
	    datePubli: '05/2012',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'Aprenda a programar agora! Este livro apresenta uma abordagem totalmente prática. Uma didática pensada no iniciante, com a qual os conceitos são apresentados com motivações práticas, através do surgimento da necessidade para depois mostrar a solução.',
	    writer: 'Paulo Silveira',
	    aboutWriter: 'Paulo Silveira, @paulo_caelum, é bacharel e mestre em Ciência da Computação pela USP, possui mais de 10 anos de experiência com desenvolvimento, passando pela Alemanha e pelo IBOPE. Coordena os cursos da Caelum nos cursos de verão da USP. Um dos fundadores do GUJ.com.br e é editor técnico da revista Mundo Java.',
	    writerImg: 'assets/image/writers/paulo-silveira.png',
	    bigImageUrl: 'assets/image/books/LogicadeProgramacao.png',
	    middleImageUrl: 'assets/image/books/LogicadeProgramacao.png',
	    smallImageUrl: 'assets/image/books/LogicadeProgramacao.png'
    },
    {
        id: 17,
        title: 'java 9',
        upon: 'Interativo, reativo e modularizado',
        about: 'Java',
        section: 'programacao',
        numPages: 273,
        datePubli: '09/2017',
        pricePrinted: 55.92,
        priceEbook: 23.92,
        pricePackage: 67.92,
        description: 'Com mais de 20 anos de plataforma, um novo Java surge com novidades importantes. O destaque especial vai para o sistema de módulos, o Jigsaw, e a modularização do próprio JDK. A linguagem também ficou interativa, com a adição de uma ferramenta de REPL (Read-Eval-Print Loop), e mais reativa, com uma API de fluxos inteiramente dedicada aos famosos Reactive Streams',
        writer: 'Rodrigo Turini',
        aboutWriter: 'Rodrigo Turini é Bacharel em Ciência da Computação e líder técnico na Alura, a plataforma de cursos online do Grupo Caelum. Desenvolve em diferentes linguagens, mas tem um envolvimento muito forte com o Java, sendo membro ativo da JCP e de expert groups do JavaEE. Turini participa ativamente da comunidade em blogs, fóruns, listas de discussões e também em eventos nacionais e internacionais. É um dos líderes de desenvolvimento do VRaptor, e contribui para diversos outros projetos e manifestos open source. Gosta de estudar continuamente as melhores práticas da orientação a objetos, programação funcional e reativa.',
        writerImg: 'assets/image/writers/rodrigo-turini.png',
        bigImageUrl: 'assets/image/books/Java9.png',
        middleImageUrl: 'assets/image/books/Java9.png',
        smallImageUrl: 'assets/image/books/Java9.png'
    }, {
       id: 18,
       title: 'apache kafka e spring boot',
       upon: 'Comunicação assíncrona entre microsserviços',
       about: 'Java',
       section: 'programacao',
       numPages: 189,
       datePubli: '01/2022',
       pricePrinted: 55.92,
       priceEbook: 31.92,
       pricePackage: 59.92,
       description: 'Pensar em comunicação assíncrona entre microsserviços é um caminho interessante quando a aplicação demanda serviços que podem demorar para responder. Para evitar problemas de timeouts e retentativas, utilizam-se filas ou tópicos, aos quais um processo adiciona uma mensagem informando o processamento a ser feito e outro a recebe quando estiver disponível e executa. O Kafka é atualmente um dos principais sistemas para a implementação de processamento assíncrono. Além de disponibilizar os tópicos para a produção e consumo de mensagens, suas diversas funcionalidades facilitam a implementação de nossas aplicações, com a distribuição e o balanceamento de carga entre os consumidores e o processamento de fluxos de dados.',
       writer: 'Eduardo Felipe Zambom Santana',
       aboutWriter: 'Eduardo Felipe Zambom Santana tem mais de 15 anos de experiência em Engenharia de Software. Trabalha principalmente como Java, já tendo trabalhado com os principais frameworks da linguagem como Struts, JSF e Spring. Também tem bastante experiência em outras linguagens como Python e Erlang. Formou-se em Ciência da Computação na UFSCar (2007), fez mestrado também na UFSCar (2010) e doutorado na USP (2019) trabalhando na área de sistemas distribuídos.',
       writerImg: 'assets/image/writers/eduardo-felipe.png',
       bigImageUrl: 'assets/image/books/Apache-Kafka.png',
       middleImageUrl: 'assets/image/books/Apache-Kafka.png',
       smallImageUrl: 'assets/image/books/Apache-Kafka.png' 
    }, 
    {
        id: 19,
	    title: 'back-end java',
	    upon: 'Microsserviços, Spring Boot e Kubernetes',
	    about: 'Java',
	    section: 'programacao',
	    numPages: 143,
	    datePubli: '03/2021',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'A arquitetura dos sistemas de software vem sofrendo diversas revoluções nos últimos anos, desde os grandes monólitos até os microsserviços. Atualmente, para a plataforma Java, o framework mais utilizado para desenvolver microsserviços é o Spring Boot, que facilita a configuração e o uso de bibliotecas necessárias. Mas para executar uma aplicação inteira, tanto em um ambiente local quanto de produção, é necessário rodar e configurar todos os serviços e permitir que eles se comuniquem. Hoje é essencial que a pessoa desenvolvedora back-end conheça, além da linguagem de programação, algumas dessas ferramentas para a execução da aplicação em um ambiente de produção. É esse o objetivo dos contêineres Docker e do Kubernetes.',
	    writer: 'Eduardo Felipe Zambom Santana',
	    aboutWriter: 'Eduardo Felipe Zambom Santana tem mais de 15 anos de experiência em Engenharia de Software. Trabalha principalmente como Java, já tendo trabalhado com os principais frameworks da linguagem como Struts, JSF e Spring. Também tem bastante experiência em outras linguagens como Python e Erlang. Formou-se em Ciência da Computação na UFSCar (2007), fez mestrado também na UFSCar (2010) e doutorado na USP (2019) trabalhando na área de sistemas distribuídos.',
	    writerImg: 'assets/image/writers/eduardo-felipe.png',
	    bigImageUrl: 'assets/image/books/Back-EndJava.png',
	    middleImageUrl: 'assets/image/books/Back-EndJava.png',
	    smallImageUrl: 'assets/image/books/Back-EndJava.png'
    },
    {
        id: 20,
	    title: 'design patterns com java',
	    upon: 'Projeto orientado a objetos guiado por padrões',
	    about: 'Java',
	    section: 'programacao',
	    numPages: 334,
	    datePubli: '11/2012',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Não é trivial compreender bem os design patterns. Entender quando aplicá-los é algo que qualquer desenvolvedor deve saber. Nesse livro, você aprenderá com exemplos práticos e bem contextualizados como aplicar os padrões e em quais situações um é mais indicado que o outro. Diferencie as características particulares de cada padrão, crie aplicações que usam o melhor da orientação a objetos em seu favor e desenvolva aplicações que você conseguirá manter para sempre!',
	    writer: 'Eduardo Guerra',
	    aboutWriter: 'Eduardo Guerra é desenvolvedor de frameworks, editor-chefe da revista MundoJ e pesquisador do Instituto Nacional de Pesquisas Espaciais (INPE). Foi professor do Instituto Tecnológico de Aeronáutica (ITA), onde concluiu sua graduação, mestrado e doutorado. Suas pesquisas se concentram nas áreas de design, arquitetura e teste de software. Possui diversas certificações da plataforma Java e experiência como arquiteto de software. Participa de projetos de frameworks open-source, como SwingBean, Esfinge e ClassMock. Ele acredita que um bom software se faz mais com criatividade do que com código e vive em busca de melhores formas para seu desenvolvimento. Está no Twitter como @emguerra.',
	    writerImg: 'assets/image/writers/eduardo-guerra.png',
	    bigImageUrl: 'assets/image/books/DesignPatternsJava.png',
	    middleImageUrl: 'assets/image/books/DesignPatternsJava.png',
	    smallImageUrl: 'assets/image/books/DesignPatternsJava.png'
    }, 
    {
        id: 21,
	    title: 'python',
	    upon: 'Escreva seus primeiros programas',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 269,
	    datePubli: '09/2015',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Python é a principal linguagem de programação utilizada no Google e repleta de funcionalidades interessantes. Neste livro, Felipe Cruz vai introduzi-lo ao Python 3, a versão mais atual, mostrando seu funcionamento, sintaxe, manipulação de arquivos, tratamento de exceções, estruturas de dados, a biblioteca padrão e tudo o que você precisa saber para começar a programar nessa linguagem.',
	    writer: 'Felipe Cruz',
	    aboutWriter: 'Felipe Cruz é desenvolvedor de software há 10 anos. Trabalhou no mercado corporativo e de startups e recentemente atua como Cientista de Dados, área onde reencontrou sua paixão pela construção de software. Mestrando em Computação pela PUC-Rio, também estuda Aprendizado de Máquinas e atualmente busca novas formas de resolver o problema da recomendação e o aprendizado não supervisionado de atributos. Pythonista há 6 anos, palestrante e participante de diversas Python Brasil, sempre buscou compartilhar conhecimento e aprender cada vez mais sobre a linguagem e o ecossistema ao longo desses anos.',
	    writerImg: 'assets/image/writers/felipe-cruz.png',
	    bigImageUrl: 'assets/image/books/Python.png',
	    middleImageUrl: 'assets/image/books/Python.png',
	    smallImageUrl: 'assets/image/books/Python.png'
    },
    {
        id: 22,
	    title: 'trilhas python',
	    upon: 'Programação multiparadigma e desenvolvimento Web com Flask',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 277,
	    datePubli: '06/2018',
	    pricePrinted: 55.92,
	    priceEbook: 31.91,
	    pricePackage: 67.92,
	    description: 'Neste livro, Eduardo Pereira apresenta tópicos de programação em Python que vão do básico ao avançado. Você verá desde estrutura de dados, funções e decoradores e criará um Jogo da Velha seguindo o paradigma de Programação Estruturada, aprimorando-o com Orientação a Objetos. Em seguida, são abordados tópicos mais avançados da linguagem, como compreensões e geradores, que são fundamentais para a Programação Funcional em Python. Por último, você aplicará o conhecimento de programação Python para o desenvolvimento Web, criando uma aplicação de streaming de música, com o framework Flask, juntamente com uma Database Abstraction Layer (PyDAL) para a integração da aplicação com banco de dados.',
	    writer: 'Eduardo Pereira',
	    aboutWriter: 'Eduardo S. Pereira é mestre e doutor em Astrofísica, pelo Instituto Nacional de Pesquisas Espaciais (INPE). Possui graduação em Física pela Universidade Federal de São João Del-Rei. Também realizou pós-doutorado em Astrofísica, pelo INPE, e em Astronomia Observacional/Computacional, pela Universidade de São Paulo (USP). Atua principalmente nos seguintes temas de pesquisa: cosmologia, ondas gravitacionais, astrofísica computacional, processamento de imagens e inteligência artificial. Atualmente, é professor do curso de Ciência da Computação da Faculdade Anhanguera, e Tutor no curso de física na Universidade Virtual de São Paulo (UNIVESP). Trabalha com Python há mais de 6 anos.',
	    writerImg: 'assets/image/writers/eduardo-pereira.png',
	    bigImageUrl: 'assets/image/books/TrilhasPython.png',
	    middleImageUrl: 'assets/image/books/TrilhasPython.png',
	    smallImageUrl: 'assets/image/books/TrilhasPython.png'
    },
    {
        id: 23,
	    title: 'flask de a - z',
	    upon: 'Crie aplicações web mais completas e robustas em Python',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 223,
	    datePubli: '10/2019',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Flask é um dos melhores frameworks para se trabalhar no Python atualmente. Por ser uma ferramenta robusta e completa, ela permite que a aplicação Web seja construída de forma a atender às necessidades de seu usuário final, ao mesmo tempo em que flexibiliza o fluxo de desenvolvimento de uma equipe. Flask interage de forma excelente com SQLAlchemy, uma biblioteca ORM muito interessante e completa, que nos permite trabalhar com diversos bancos de dados relacionais dentro do Python com segurança, e isso trará muitas vantagens para nossos estudos.',
	    writer: 'Tiago Silva',
	    aboutWriter: 'Tiago Silva é graduado em Análise e Desenvolvimento de Sistemas pelas Faculdades Integradas Simonsen, professor na área de Tecnologia há mais de 6 anos, atualmente trabalha como cientista de dados onde desenvolve sistemas e scripts em Python focados em processamento de um alto volume de dados. Especialista em Python, Google Maps e Adobe Muse é fundador do Canal Digital Cursos, onde existem cursos inteiramente online focados em ajudar pessoas a entrarem para o mercado de trabalho.',
	    writerImg: 'assets/image/writers/tiago-silva.png',
	    bigImageUrl: 'assets/image/books/FlaskAZ.png',
	    middleImageUrl: 'assets/image/books/FlaskAZ.png',
	    smallImageUrl: 'assets/image/books/FlaskAZ.png'
    },
    {
        id: 24,
	    title: 'django de a - z',
	    upon: 'Crie aplicações web rápidas, seguras e escaláveis com Python',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 320,
	    datePubli: '04/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Considerado o framework mais popular no Python, Django é uma ferramenta completa e robusta, que nos permite criar uma aplicação web de forma rápida e consistente. Se você quer avançar no mercado de Python ou ingressar nele, ao dominar Django você terá as habilidades necessárias para construir enormes aplicações que poderão ser utilizadas por pequenas, médias e grandes corporações.',
	    writer: 'Tiago Silva',
	    aboutWriter: 'Tiago Silva é graduado em Análise e Desenvolvimento de Sistemas pelas Faculdades Integradas Simonsen, professor na área de Tecnologia há mais de 6 anos, atualmente trabalha como cientista de dados onde desenvolve sistemas e scripts em Python focados em processamento de um alto volume de dados. Especialista em Python, Google Maps e Adobe Muse é fundador do Canal Digital Cursos, onde existem cursos inteiramente online focados em ajudar pessoas a entrarem para o mercado de trabalho.',
	    writerImg: 'assets/image/writers/tiago-silva.png',
	    bigImageUrl: 'assets/image/books/DjangoAZ.png',
	    middleImageUrl: 'assets/image/books/DjangoAZ.png',
	    smallImageUrl: 'assets/image/books/DjangoAZ.png'
    },
    {
        id: 25,
	    title: 'ionic 6',
	    upon: 'Desenvolvimento multiplataforma para dispositivos móveis',
	    about: 'iOS',
	    section: 'mobile',
	    numPages: 358,
	    datePubli: '01/2022',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Everton Coimbra de Araújo aborda o Ionic 6, junto de frameworks específicos, como o Capacitor, que possibilita a transformação de uma aplicação Ionic em uma aplicação híbrida. Você vai aprender na prática com um projeto de exemplo que pode ser executado, com recursos nativos, nos sistemas operacionais iOS e Android, testando-o em emuladores e em dispositivos físicos. Dentre as funcionalidades exploradas, estão: persistência de dados, tanto local como por meio do SQLite e Firestore, criação da interface com o usuário, navegação entre páginas, operações CRUD, e ainda, o uso de recursos como câmera e álbum de fotografia.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/Ionic-6.png',
	    middleImageUrl: 'assets/image/books/Ionic-6.png',
	    smallImageUrl: 'assets/image/books/Ionic-6.png'
    },
    {
        id: 26,
	    title: 'xamarin forms e MVVM',
	    upon: 'Persistência local com Entity Framework Core',
	    about: 'iOS',
	    section: 'mobile',
	    numPages: 470,
	    datePubli: '08/2021',
	    pricePrinted: 71.92,
	    priceEbook: 23.92,
	    pricePackage: 83.92,
	    description: 'Neste livro, Everton Coimbra demonstra na prática como criar uma aplicação para iOS e Android com Xamarin e Xamarin Forms, utilizando a linguagem C#. Você vai desenvolver um projeto de exemplo que lidará com cadastro, imagens e base de dados, aplicando o modelo MVVM (Model, View, ViewModel). Para o acesso à base de dados, será feito uso do Entity Framework Core, API da Microsoft para persistência de objetos em um paradigma relacional. O autor ainda complementa o material com a implementação de serviços REST em um servidor Web, para serem consumidos em sua aplicação Xamarin. Tudo isso em uma arquitetura bem elaborada e flexível, que você poderá comprovar.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/XamarinFormseMVVM.png',
	    middleImageUrl: 'assets/image/books/XamarinFormseMVVM.png',
	    smallImageUrl: 'assets/image/books/XamarinFormseMVVM.png'
    },
    {
        id: 27,
	    title: 'kotlin com android',
	    upon: 'Crie aplicativos de maneira fácil e divertida',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 346,
	    datePubli: '07/2018',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Kassiano Resende apresenta a linguagem Kotlin tanto para quem já conhece Java ou não, com uma didática prática e divertida. Você verá todos os passos necessários para construir e publicar na Play Store aplicações mobile em Kotlin, no ambiente de desenvolvimento Android Studio. O escopo das aplicações apresentadas no livro vai além das funcionalidades da linguagem, com a utilização de banco de dados, acesso a APIs REST e funcionalidades dos smartphones, como notificações, acesso à galeria de imagens, câmera e localização através de GPS.',
	    writer: 'Kassiano Resende',
	    aboutWriter: 'Kassiano Resende trabalha com desenvolvimento de software desde 2008, e desde então teve sua carreira voltada a plataformas web e mobile. Atualmente, é professor do SENAI-SP, ministrando disciplinas de programação para dispositivos móveis e projetos de software. Apaixonado por open source, está sempre estudando novas tecnologias.',
	    writerImg: 'assets/image/writers/kassiano-resende.png',
	    bigImageUrl: 'assets/image/books/KotlincomAndroid.png',
	    middleImageUrl: 'assets/image/books/KotlincomAndroid.png',
	    smallImageUrl: 'assets/image/books/KotlincomAndroid.png'
    },
    {
        id: 28,
	    title: 'app inventor',
	    upon: 'Seus primeiros aplicativos Android',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 305,
	    datePubli: '11/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Nelson e Valéria Gerbelli têm como objetivo proporcionar aos estudantes, educadores e entusiastas por tecnologia o primeiro passo no mundo da programação para dispositivos móveis por meio do App Inventor. Após ser apresentado ao ambiente, você aprenderá na prática a desenvolver alguns aplicativos do zero, partindo de alguns cálculos, até chegar a resultados mais complexos, com um recurso de localização de GPS, tradução de idioma e desenvolvendo um projeto final completo. Dentre as funcionalidades, estão o compartilhamento com outros aplicativos como o WhatsApp, a conexão a um banco de dados em MySQL, e a disponibilização do aplicativo na loja do Google Play Store.',
	    writer: 'Nelson Fabbri Gerbelli',
	    aboutWriter: 'Nelson Fabbri Gerbelli é Tecnólogo em Processamento de Dados pela faculdade FAINAM, pós-graduado em Análise de Sistemas pela faculdade ESAN. Pedagogo e possui licenciatura plena em Informática. É professor em cursos de TI no Centro Estadual de Educação Tecnológica Paula Souza do Estado de São Paulo nas ETECs, atuando principalmente nas seguintes disciplinas: Tecnologia para mobilidade, técnicas de programação para internet e desenvolvimento de softwares com o Visual Studio.Net.',
	    writerImg: 'assets/image/writers/nelson-fabbri.png',
	    bigImageUrl: 'assets/image/books/AppInventor.png',
	    middleImageUrl: 'assets/image/books/AppInventor.png',
	    smallImageUrl: 'assets/image/books/AppInventor.png'
    },
    {
        id: 29,
	    title: 'entrega contínua em android',
	    upon: 'Como automatizar a distribuição de apps',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 190,
	    datePubli: '09/2016',
	    pricePrinted: 47.92,
	    priceEbook: 23.92,
	    pricePackage: 59.92,
	    description: 'Neste livro, Roger Silva vem preencher esta lacuna, explicando como automatizar a distribuição do app para o Google Play, como executar testes automatizados sobre as suas funcionalidades e disponibilizá-lo para a equipe de testes em vários dispositivos. Você verá como tratar todos esses requisitos para que, quando um desenvolvedor comitar seu código-fonte para um repositório de código remoto, uma bateria de testes automatizados seja executada, acompanhada por uma análise de cobertura de código-fonte, verificações de regras de negócios e, por fim, chegando até a etapa de distribuição automatizada do app para o Google Play.',
	    writer: 'Roger Silva',
	    aboutWriter: 'Desde 2012 com atuação no setor de TI, é Engenheiro de Software com forte experiência em desenvolvimento mobile. Já trabalhou também com desenvolvimento front-end, back-end e em manutenção de software legado. Oficialmente certificado Scrum Master (pela Scrum Alliance), é apaixonado por trabalhar com todas as correntes do Agile — Scrum, Lean, Kanban e XP. Bacharel em Ciência da Computação pela Universidade Federal do Rio Grande do Sul (UFRGS), é também blogueiro e palestrante em eventos sobre tecnologia. Nas horas vagas, é frequentador assíduo do estádio do seu time de coração, game maníaco desde os quatro anos de idade e viciado em happy hours.',
	    writerImg: 'assets/image/writers/roger-silva.png',
	    bigImageUrl: 'assets/image/books/EntregaContinuaAndroid.png',
	    middleImageUrl: 'assets/image/books/EntregaContinuaAndroid.png',
	    smallImageUrl: 'assets/image/books/EntregaContinuaAndroid.png'
    },
    {
        id: 30,
	    title: 'iniciando com flutter framework',
	    upon: 'Desenvolva aplicações móveis no Dart Side!',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 173,
	    datePubli: '07/2020',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'Neste livro, Leonardo Marinho mostra quais dores o Flutter veio para curar, com a criação de aplicativos verdadeiramente performáticos, atrativos e multiplataforma. Você conhecerá desde a arquitetura de software fantástica por baixo dele e as razões pelas quais Dart foi a linguagem escolhida para programar nele, verá que tudo será organizado com Widgets e poderá aproveitá-los ao máximo. Pelo caminho, colocará em prática as principais etapas da criação de um aplicativo, como gerenciamento de dependências, requisições http, banco de dados local, testes automatizados, estilização e muito mais!',
	    writer: 'Leonardo H Marinho',
	    aboutWriter: 'Leonardo é graduado em Análise e Desenvolvimento de Sistemas e atualmente é mestrando em sistemas de informação pela Universidade Federal do Rio de Janeiro (UFRJ). Desenvolvedor Full Stack apaixonado por criar aplicativos para dispositivos móveis (Android e IOS) com tecnologias como Ionic e Flutter. Organizador da conferência OpenLabs, atualmente a maior conferência tecnológica da região serrana carioca. Nos finais de semana prepara aulas para seus cursos de programação em modalidade EaD, didática e transmissão de conhecimento são suas grandes paixões. É membro fundador da comunidade Dart Lang Brasil. Gosta de Star Wars e café.',
	    writerImg: 'assets/image/writers/leonardo-h-marinho.png',
	    bigImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png',
	    middleImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png',
	    smallImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png'    
    },
    {
        id: 31,
	    title: 'react native',
	    upon: 'Desenvolvimento de aplicativos mobile com React',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 189,
	    datePubli: '08/2021',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Bruna Escudelario e Diego Pinho vão desde os primeiros passos com React Native até o desenvolvimento de aplicações que consomem serviços na internet (APIs). No meio deste percurso, você vai aproveitar e estudar o funcionamento da biblioteca React para web, afinal, todos os conceitos trabalhados nela também são usados aqui. Você verá o que é o JSX e como criar um componente das mais diversas formas, quais são as principais dependências, o que são propriedades e estados, estilos por meio do Flexbox e CSS, navegação de telas, quais são as principais funções do ciclo de vida de um componente, como passar informações de um componente para outro, consumir serviços da internet e atualizar os componentes com as respostas, até chegar à última grande novidade do React 16, os Hooks. Este livro foi estruturado de modo que os tópicos se complementem e se tornem gradativamente mais complexos ao decorrer da leitura, mas sempre apoiados por códigos contextualizados em casos de usos reais, seguindo as boas práticas adotadas pelo mercado e pela comunidade desenvolvedora.',
	    writer: 'Bruna Escudelario',
	    aboutWriter: 'Bruna Escudelario é Desenvolvedora Web com experiência na área de front-end com as tecnologias e frameworks: HTML5, CSS3, JavaScript, Node.js, Gulp.js, entre outras. Tem bacharelado em Ciência da Computação pela Pontifícia Universidade Católica de São Paulo (PUC-SP) e é entusiasta em desenvolvimento de jogos.',
	    writerImg: 'assets/image/writers/bruna-escudelario.png',
	    bigImageUrl: 'assets/image/books/ReactNative.png',
	    middleImageUrl: 'assets/image/books/ReactNative.png',
	    smallImageUrl: 'assets/image/books/ReactNative.png'  
    },
    {
        id: 32,
	    title: 'cordova avançado e phoneGap',
	    upon: 'Um guia detalhado do zero à publicação',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 292,
	    datePubli: '03/2018',
	    pricePrinted: 63.92,
	    priceEbook: 23.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Diogo Machado se volta aos profissionais da área de tecnologia que já possuam uma experiência básica com Cordova e PhoneGap, mas que desejam expandir suas possibilidades e tornar suas aplicações mais robustas. Ao acompanhar a criação de um projeto completo, você verá como utilizar os principais plug-ins, integrar a plataforma Firebase, construir elementos visuais do zero usando código web e, o melhor, com todo o processo de publicação detalhado em Android e iOS.',
	    writer: 'Diogo Machado',
	    aboutWriter: 'Diogo Souza Machado, sou desenvolvedor web/mobile e desde 2010 trabalho com PHP, MySQL, JavaScript, HTML e CSS. Ao longo desses, anos adquiri experiência e maturidade na área. Estou sempre estudando, gosto de testar coisas novas, mas algumas tecnologias são minhas favoritas, como o Angular, PhoneGap/Cordova, CSS3 e HTML5. Atualmente, trabalho como Analista de Sistemas na Unimed Sul Capixaba, mas também produzo aplicativos e sistemas para outras empresas, ministro palestras, cursos e escrevo artigos no site.',
	    writerImg: 'assets/image/writers/diogo-machado.png',
	    bigImageUrl: 'assets/image/books/Cordova_Amazon.png',
	    middleImageUrl: 'assets/image/books/Cordova_Amazon.png',
	    smallImageUrl: 'assets/image/books/Cordova_Amazon.png'          
    },
    {
        id: 33,
	    title: 'xamarin forms',
	    upon: 'Desenvolvimento de aplicações móveis multiplataforma',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 303,
	    datePubli: '09/2020',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Everton Coimbra traz, na prática, o desenvolvimento de aplicações multiplataforma com o Xamarin e Xamarin Forms, apresentando conceitos como componentes, ações, acesso a bases de dados via SQLite, mapas e muito mais. Explorando as potencialidades do Xamarin e de tecnologias afins, você acompanhará a construção de um aplicativo para diferentes dispositivos móveis a partir de uma mesma estrutura de código.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/XamarinForms.png',
	    middleImageUrl: 'assets/image/books/XamarinForms.png',
	    smallImageUrl: 'assets/image/books/XamarinForms.png'          
    },
    {
        id: 34,
	    title: 'aplicações mobile híbridas com Cordova e PhoneGap',
	    upon: 'Aprenda a construir apps híbridos',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 202,
	    datePubli: '02/2016',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Sérgio Lopes mostra o Cordova, a solução para Apps híbridas mais usada no mundo. Escreva um único código baseado em HTML5 e tenha Apps de verdade para iOS, Android e Windows Phone. Com projetos práticos, você vai ver Cordova desde o início até casos complexos de integração com hardware. Vai entender onde o PhoneGap se encaixa e até criar uma App com Ionic.',
	    writer: 'Sérgio Lopes',
	    aboutWriter: 'Sérgio Lopes programa para Web desde 2000, de preferência front-end. É instrutor e desenvolvedor na Caelum desde 2004 e possui bacharelado em Ciência da Computação na USP. Também é moderador do GUJ, palestrante de diversos eventos e ativo participante da comunidade. Nos últimos tempos, tem focado em dispositivos móveis e as implicações para a Web. Tem um blog pessoal onde fala muito de front-end e uma conta no Twitter.',
	    writerImg: 'assets/image/writers/sergio-lopes.png',
	    bigImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png',
	    middleImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png',
	    smallImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png'          
    },
    {
        id: 35,
	    title: 'roadmap back-end',
	    upon: 'Conhecendo o protocolo HTTP e arquiteturas REST',
	    about: 'Web',
	    section: 'infraestrutura',
	    numPages: 151,
	    datePubli: '04/2022',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 71.92,
	    description: 'Neste livro, Victor Osório dá as bases para que você vá além dos frameworks, conhecendo os protocolos e arquiteturas envolvidas no seu trabalho do dia a dia. Você verá como utilizar e implementar o protocolo com Quarkus, chegando aos estilos arquiteturais usados através do HTTP, com REST e outros, para expandir a sua capacidade de resolução e seu leque de opções no back-end.',
	    writer: 'Victor Osório',
	    aboutWriter: 'Engenheiro de Software no time de produtos da divisão de Redes da Amdocs, trabalhando com Java desde 2004, tem longa experiência em construção de diversos sistemas, mas agora focado como Back-end trabalhando em sistemas distribuídos e integrados via Apache Kafka. Vida longa ao Java!',
	    writerImg: 'assets/image/writers/victor-osorio.png',
	    bigImageUrl: 'assets/image/books/RoadmapBack-end.png',
	    middleImageUrl: 'assets/image/books/RoadmapBack-end.png',
	    smallImageUrl: 'assets/image/books/RoadmapBack-end.png'         
    },
    {
        id: 36,
	    title: 'pentest em aplicações web',
	    upon: 'Avalie a segurança contra ataques web com testes de invasão no Kali Linux',
	    about: 'Web',
	    section: 'infraestrutura',
	    numPages: 267,
	    datePubli: '11/2021',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, José Augusto mostra como validar as defesas de uma aplicação web do ponto de vista do atacante. Você aprenderá os conceitos e vulnerabilidades fundamentais como XSS, CRSF e SSRF, utilizará ferramentas de teste de invasão no Kali Linux, como o Metasploit, e realizará a exploração das fragilidades a fim de provar na prática seus impactos nas organizações.',
	    writer: 'José Augusto de Almeida Jr.',
	    aboutWriter: 'José Augusto é especialista em segurança ofensiva e doutorando em segurança da informação pela UnB. Ao decorrer da carreira, certificou-se na área com 3 certificações reconhecidas no mercado de pentest: OSWP, OSCP e OSCE. Além disso, é mestre em segurança cibernética, pós-graduado em segurança da informação e possui uma especialização em guerra cibernética pelo centro de instrução de guerra eletrônica do exército. José formou-se bacharel sistemas de informação e iniciou na área de informática em 2012, após a conclusão do curso técnico em informática pela ETEC Guaratinguetá. Antes de trabalhar com segurança, vivenciou 2 anos na área de desenvolvimento com Java, PHP, JavaScript, etc. Em 2014 foi aprovado em concurso militar para especialidade de sistemas de informação na Força Área Brasileira e de 2015 a 2021 trabalhou com foco na área de militar. Hoje, José é professor e Especialista em red team no setor privado.',
	    writerImg: 'assets/image/writers/jose-augusto.png',
	    bigImageUrl: 'assets/image/books/PentestAppWeb.png',
	    middleImageUrl: 'assets/image/books/PentestAppWeb.png',
	    smallImageUrl: 'assets/image/books/PentestAppWeb.png'        
    },
    {
        id: 37,
	    title: 'apis rest',
	    upon: 'Seus serviços prontos para o mundo real',
	    about: 'Web',
	    section: 'infraestrutura',
	    numPages: 321,
	    datePubli: '01/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Alexandre Saudate aborda os serviços REST pelo viés prático, explicando os conceitos conforme vamos desenvolvendo uma aplicação ao longo do livro. Você vai aprender como criar um cliente para o serviço REST do Google Maps, além de como estabelecer relacionamentos, implementar testes e criar camadas de segurança. Na segunda parte do livro, você entrará ainda mais a fundo sobre APIs e até implementará algumas com ferramentas como o API Gateway da AWS e o Ngrok. Isso trará o conhecimento para que os serviços REST sejam realmente aproveitados, de modo a estarem prontos para os desafios que aparecerão uma vez que o grande público passe a utilizar sua aplicação.',
	    writer: 'Alexandre Saudate',
	    aboutWriter: 'Alexandre Saudate é graduado em Sistemas de Informação pela Universidade de São Paulo (USP). Trabalha com desenvolvimento desde 2005, tendo realizado pesquisa e desenvolvimento sobre diversos tipos de arquitetura, sendo muito conhecido por seu trabalho com SOA e mais recentemente com microsserviços. Desenvolveu projetos para diversas empresas, como Porto Seguro, Serasa, iG, Netshoes, Stelo e outras. Hoje, é Especialista de Software e atua primordialmente com desenvolvimento em Java, Kotlin, e microsserviços na AWS.',
	    writerImg: 'assets/image/writers/alexandre-saudate.png',
	    bigImageUrl: 'assets/image/books/APIsREST.png',
	    middleImageUrl: 'assets/image/books/APIsREST.png',
	    smallImageUrl: 'assets/image/books/APIsREST.png'        
    },
    {
        id: 38,
	    title: 'desconstruindo a web',
	    upon: 'As tecnologias por trás de uma requisição',
	    about: 'Web',
	    section: 'infraestrutura',
	    numPages: 255,
	    datePubli: '08/2016',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Willian Molinari nos mostra separadamente cada uma das peças de uma requisição web. Utilizando uma página HTML como exemplo, faremos um estudo unificado e focado no entendimento de como a internet funciona. Passaremos pela criação visual da interface do navegador, pela montagem dos pacotes dentro do kernel do sistema operacional, pelos dispositivos de rede da internet, e até mesmo pela integração do código da aplicação com o servidor web.',
	    writer: 'Willian Molinari',
	    aboutWriter: 'Willian Molinari, mais conhecido como PotHix, é formado em Sistemas de informação e trabalha com desenvolvimento de software há mais de 10 anos. É um dos fundadores do Guru-SP, ajudando na organização do grupo desde 2008. No seu tempo livre, ele desenvolveu alguns jogos com HTML5 e Javascript, sendo o Skeleton Jigsaw o último deles. Já fez dezenas de palestras, passando por mais de 7 estados brasileiros e foi revisor técnico de dois livros. Mais informações podem ser encontradas no seu blog pessoal: http://pothix.com.',
	    writerImg: 'assets/image/writers/willian-molinari.png',
	    bigImageUrl: 'assets/image/books/DesconstruindoaWeb.png',
	    middleImageUrl: 'assets/image/books/DesconstruindoaWeb.png',
	    smallImageUrl: 'assets/image/books/DesconstruindoaWeb.png'        
    },
    {
        id: 39,
	    title: 'tuning de SQL',
	    upon: 'Melhore a performance de suas aplicações Oracle',
	    about: 'Dados',
	    section: 'infraestrutura',
	    numPages: 523,
	    datePubli: '12/2021',
	    pricePrinted: 79.92,
	    priceEbook: 31.92,
	    pricePackage: 83.92,
	    description: 'Neste livro, Eduardo Gonçalves demonstrará diversas técnicas para escrever instruções SQL de forma apropriada para que o otimizador do banco de dados possa escolher um plano de execução eficaz para executá-las. Por meio de técnicas, como a criação de índices, uso de sugestões (hints), ajustes de sintaxe e métodos de acesso a tabelas, além de ferramentas de auxílio de Tuning SQL, você será capaz de analisar aplicações problemáticas, gerar estatísticas para o otimizador e obter informações das instruções executadas no banco de dados Oracle. Com isso, será possível criar uma cultura de pensar em desempenho desde a análise de uma aplicação, até sua concepção e implantação.',
	    writer: 'Eduardo Gonçalves',
	    aboutWriter: 'Formado em Tecnologia da Informação, possui mais de 15 anos de experiência em análise e desenvolvimento de sistemas voltados para tecnologias Oracle. Trabalhou para grandes empresas como Lojas Renner, Mundial S.A, Tigre S.A, Pernambucanas, Engie, Portobello Cerâmica, Bematech, Positivo, Ailos entre outras. É instrutor de cursos nas linguagens Oracle SQL e Oracle PL/SQL. Atualmente, desenvolve projetos na Supero Tecnologia.',
	    writerImg: 'assets/image/writers/eduardo-goncalves.png',
	    bigImageUrl: 'assets/image/books/TuningSQL.png',
	    middleImageUrl: 'assets/image/books/TuningSQL.png',
	    smallImageUrl: 'assets/image/books/TuningSQL.png'        
    },
    {
        id: 40,
	    title: 'akka & akka streams',
	    upon: 'Construa sistemas distribuídos com atores',
	    about: 'Dados',
	    section: 'infraestrutura',
	    numPages: 283,
	    datePubli: '12/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Alexandre Lourenço abordará arquiteturas distribuídas simulando sistemas reais, como integrações com sistemas de arquivos, comunicação com Kafka e bancos de dados, entre outros. Você construirá uma API REST fictícia de um e-commerce e entenderá como os frameworks Akka e Akka Streams, os paradigmas de streams e de atores podem ajudar a cumprir essa missão.',
	    writer: 'Alexandre Lourenço',
	    aboutWriter: 'Formado em Ciência da Computação pela PUC-SP com pós-graduação pelo UNIBTA, Alexandre Eleutério Santos Lourenço trabalha com desenvolvimento de software desde 2003. Atuou com diversos frameworks, ferramentas e linguagens, como Elasticsearch, Kafka, Docker, Kubernetes, Java, Python, Scala, entre outras e, é claro, Akka Streams, tendo trabalhado com a tecnologia em desenvolvimentos ligados a integrações e sistemas de geolocalização.',
	    writerImg: 'assets/image/writers/alexandre-lourenco.png',
	    bigImageUrl: 'assets/image/books/Akka&AkkaStreams.png',
	    middleImageUrl: 'assets/image/books/Akka&AkkaStreams.png',
	    smallImageUrl: 'assets/image/books/Akka&AkkaStreams.png'        
    },
    {
        id: 41,
	    title: 'machine learning',
	    upon: 'Introdução à classificação',
	    about: 'Dados',
	    section: 'infraestrutura',
	    numPages: 407,
	    datePubli: '10/2017',
	    pricePrinted: 71.92,
	    priceEbook: 31.92,
	    pricePackage: 83.92,
	    description: 'Neste livro, Guilherme Silveira e Bennett Bullock mostram como o computador aprende com uma base de dados e algoritmos para responder perguntas do dia a dia, com uma aplicabilidade crescente no mundo dos negócios, cada vez mais apurada, conforme mais dados estão disponíveis. Por meio de variáveis numéricas e categóricas, você vai treinar modelos matemáticos computacionais em Python que nos ajudam a tomar decisões e prever comportamentos, como quando um funcionário está próximo de pedir demissão ou qual será o próximo passo de um usuário em um site.',
	    writer: 'Bennett Bullock',
	    aboutWriter: 'Bennett Bullock Bennett Bullock é um profissional com 14 anos de experiência no campo de aprendizagem de máquina e NLP. Ele tem desenvolvido tecnologias de classificação de texto, de pesquisa (na qual obteve uma patente), e de análise financeira para vários clientes no governo americano e na comunidade financeira. Ele é mestre em linguística árabe pela Universidade de Georgetown, e em bioengenharia pelo MIT.',
	    writerImg: 'assets/image/writers/bennett-bullock.png',
	    bigImageUrl: 'assets/image/books/MachineLearning.png',
	    middleImageUrl: 'assets/image/books/MachineLearning.png',
	    smallImageUrl: 'assets/image/books/MachineLearning.png'
    },
    {
        id: 42,
	    title: 'teoria dos grafos',
	    upon: 'Uma abordagem prática em Java',
	    about: 'Dados',
	    section: 'infraestrutura',
	    numPages: 203,
	    datePubli: '11/2020',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, João Paulo Maida apresenta a Teoria dos Grafos, desde suas diversas aplicações, definições de conceitos como vértice, aresta, árvores, suas funções e características. Você vai aprender sobre métodos de buscas, análise de caminhos, construção e redução de árvores, conforme desenvolve na prática uma aplicação em Java para aplicar o que foi visto. Para isso, o livro aborda os algoritmos utilitários que respondem a questões do cotidiano: o de Dijkstra, Floyd-Warshall e Prim, tudo isso de forma descomplicada e leve.',
	    writer: 'João Paulo Maida',
	    aboutWriter: 'João Paulo Maida é um carioca "sangue bom", amante de tecnologia, livros, quadrinhos e de praticar exercícios físicos. Faz capoeira, com a qual ainda está aprendendo que nem sempre o básico é fácil. Se formou em Ciência da Computação pela Universidade Veiga de Almeida em 2012 e em 2016 terminou seu MBA em Engenharia de Software pela UFRJ. Trabalha com T.I. desde 2008 e em 2010 começou sua carreira como desenvolvedor. Atualmente é consultor sênior de middleware na Red Hat, uma das gigantes do opensource, onde realiza esta função com muita felicidade desde 2019.',
	    writerImg: 'assets/image/writers/joao-paulo-maida.png',
	    bigImageUrl: 'assets/image/books/TeoriadosGrafos.png',
	    middleImageUrl: 'assets/image/books/TeoriadosGrafos.png',
	    smallImageUrl: 'assets/image/books/TeoriadosGrafos.png'        
    },
    {
        id: 43,
	    title: 'criatividade e inovação',
	    upon: 'Entre na Era das Startups',
	    about: 'Startups',
	    section: 'business',
	    numPages: 138,
	    datePubli: '09/2020',
	    pricePrinted: 47.92,
	    priceEbook: 23.92,
	    pricePackage: 59.92,
	    description: 'Neste livro, Ivam Galvão Filho apresenta uma visão de todo o processo relacionado à inovação dentro das organizações. Você verá que é uma trajetória que envolve a aquisição, preservação e gestão do conhecimento, passa pela criação de ambientes adequados, gestão de equipes criativas e adoção de comportamentos criativos pelos colaboradores, até que finalmente gera um produto, serviço ou processo inovador. Este novo artefato somente poderá revolucionar o mercado se sobreviver aos processos seguintes, e para isso o autor também aborda desenvolvimento e gestão de projetos, formas de financiamento, elaboração do Business Model Canvas, MVP, Pitch, entre outras noções importantes para todo empreendedor.',
	    writer: 'Ivam Galvão Filho',
	    aboutWriter: 'Ivam Galvão Filho é Analista Desenvolvedor de Sistema e um empreendedor. Formado em Análise e Desenvolvimento de Sistemas pelo Centro Universitário Estácio de Sá e mestrando em Engenharia do Conhecimento pela UFSC, possui ampla experiência em Startups, é considerado uma referência na área de desenvolvimento com framework Angular segundo a empresa americana CodersRank.io.',
	    writerImg: 'assets/image/writers/ivam-galvao-filho.png',
	    bigImageUrl: 'assets/image/books/CriatividadeInovacao.png',
	    middleImageUrl: 'assets/image/books/CriatividadeInovacao.png',
	    smallImageUrl: 'assets/image/books/CriatividadeInovacao.png'        
    },
    {
        id: 44,
	    title: 'guia da startup',
	    upon: 'Como startups e empresas estabelecidas podem criar produtos de software rentáveis',
	    about: 'Startups',
	    section: 'business',
	    numPages: 336,
	    datePubli: '08/2017',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Aprenda as melhores técnicas para criar o seu produto web e faça ele render dinheiro o mais rápido possível com o Guia da Startup. Da mesma maneira que diversas empresas de sucesso fizeram, como a Caelum e a Locaweb, invista em suas ideias.',
	    writer: 'Joaquim Torres',
	    aboutWriter: 'Joaquim Torres é CPO (Chief Product Officer) na ContaAzul e mentor na Endeavor e na ACE Aceleratech. Foi diretor de desenvolvimento de produtos na Locaweb por mais de 11 anos e montou sua primeira startup em 1992, um BBS que virou um dos primeiros provedores de acesso à internet do Brasil. Mantém dois blogs, o http://jocaonstuff.com e http://guiadastartup.com.br. Está no Twitter como @jocatorres.',
	    writerImg: 'assets/image/writers/joaquim-torres.png',
	    bigImageUrl: 'assets/image/books/GuiadaStartup.png',
	    middleImageUrl: 'assets/image/books/GuiadaStartup.png',
	    smallImageUrl: 'assets/image/books/GuiadaStartup.png'           
    },
    {
        id: 45,
	    title: 'a jornada do empreendedor',
	    upon: 'O herói da nossa Era',
	    about: 'Startups',
	    section: 'business',
	    numPages: 276,
	    datePubli: '07/2016',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Uma jornada é uma busca por um ideal, por um grande desafio. Para uns, a motivação é a recompensa financeira. Para outros, o desejo de fazer algo maior que si mesmos. Seja qual for o seu objetivo, para chegar lá você precisará de força de vontade sobre-humana. O empreendedor deve ser um verdadeiro herói.',
	    writer: 'Laura Mello Constantini',
	    aboutWriter: 'Laura Mello é uma dos sócios da Astella Investimentos e conselheira de algumas das empresas do portfolio da Astella. Formada em Administração de Empresas pela Fundação Getúlio Vargas, foi vice-presidente da Cicerone Capital e fez longa carreira como responsável por equity research com foco em Telecom e Tecnologia em diversas instituições financeiras. A busca por eficiência e um relacionamento saudável entre empresas e investidores foi o que sempre a entusiasmou e por isso Laura foca sua atuação em transparência e governança corporativa nas empresas.',
	    writerImg: 'assets/image/writers/laura-mello.png',
	    bigImageUrl: 'assets/image/books/Ajornadadoempreendedor.png',
	    middleImageUrl: 'assets/image/books/Ajornadadoempreendedor.png',
	    smallImageUrl: 'assets/image/books/Ajornadadoempreendedor.png'           
    },
    {
        id: 46,
	    title: 'direto ao ponto',
	    upon: 'Criando produtos de forma enxuta',
	    about: 'Startups',
	    section: 'business',
	    numPages: 263,
	    datePubli: '08/2015',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Ao trabalhar em um projeto, você não quer desperdiçar tempo, dinheiro, nem esforço construindo um produto que não vai atender às suas expectativas ou de seu cliente. Para isso, é preciso validar as hipóteses de negócio e viabilizar possíveis passos de criação com o time todo.',
	    writer: 'Paulo Caroli',
	    aboutWriter: 'Consultor principal da Thoughtworks Brazil e cofundador da AgileBrazil, Paulo Caroli possui mais de vinte anos de experiência em desenvolvimento de software, com passagem em várias corporações no Brasil, Índia e EUA. Em 2000, conheceu o eXtreme Programming e, desde então, tem focado sua experiência em processos e práticas de Gestão e Desenvolvimento Ágil. Ingressou na ThoughtWorks em 2006 e ocupou os cargos de Agile Coach, Trainer, e Gerente de Projetos. Possui os títulos de Bacharel em Ciência da Computação e M.S. em Engenharia de Software, ambos da PUC-Rio. Autor dos livros “Direto ao ponto; criando produtos de forma enxuta”, e “Fun Retrospectives; activities and ideas for making agile retrospectives more engaging”. Leia mais em www.caroli.org',
	    writerImg: 'assets/image/writers/paulo-caroli.png',
	    bigImageUrl: 'assets/image/books/DiretoaoPonto.png',
	    middleImageUrl: 'assets/image/books/DiretoaoPonto.png',
	    smallImageUrl: 'assets/image/books/DiretoaoPonto.png'           
    },
    {
        id: 47,
	    title: 'inbound marketing',
	    upon: 'Estratégias práticas para empresas e projetos',
	    about: 'Marketing Digital',
	    section: 'business',
	    numPages: 143,
	    datePubli: '06/2019',
	    pricePrinted: 39.92,
	    priceEbook: 23.92,
	    pricePackage: 47.92,
	    description: 'Se você acredita que uma estratégia de marketing vai muito além de fazer anúncios e pode envolver diversas áreas da empresa, este livro lhe será muito útil. Você vai descobrir que existe uma área dentro do marketing que une o online e o offline, e que pode até mudar o mindset das organizações. Este é o Inbound Marketing, a metodologia que tem se tornado um estilo de vida para as empresas.',
	    writer: 'Adriélly Calil',
	    aboutWriter: 'Adriélly Calil é formada em Marketing e atua na área desde 2015. Apaixonada por Marketing Digital e conteúdo, hoje lidera a área de Inbound Marketing B2C/B2B das empresas do grupo Caelum Alura, criando estratégias e executando diversas tarefas como criação de newsletters, guias de empresas, ebooks, pesquisas e participação do grupo em eventos corporativos.',
	    writerImg: 'assets/image/writers/adrielly-calil.png',
	    bigImageUrl: 'assets/image/books/InboundMarketing.png',
	    middleImageUrl: 'assets/image/books/InboundMarketing.png',
	    smallImageUrl: 'assets/image/books/InboundMarketing.png'   
    },
    {
        id: 48,
	    title: 'marketing de conteúdo',
	    upon: 'Estratégias para entregar o que seu público quer consumir',
	    about: 'Marketing Digital',
	    section: 'business',
	    numPages: 213,
	    datePubli: '12/2017',
	    pricePrinted: 55.92,
	    priceEbook: 23.92,
	    pricePackage: 67.92,
	    description: 'Em um mundo no qual tudo é informação, saber entregá-la no melhor formato ao seu público é uma das chaves do sucesso para uma estratégia de marketing de conteúdo. Através dele, as marcas podem, além de conhecer melhor o seu público, entregar exatamente o que ele quer consumir, tanto no que diz respeito ao conteúdo como ao produto.',
	    writer: 'Jonathan Lamim Antunes',
	    aboutWriter: 'Jonathan Lamim trabalha com desenvolvimento web desde 2005, e é apaixonado pelo o que faz, desde que iniciou trabalho com desenvolvimento de sites, blogs, portais, e-commerce e sistemas web dos mais variados tipos e tamanhos. Dentre as linguagens, frameworks e bancos de dados utilizados estão: HTML, CSS, JS, PHP, MySQL e CodeIgniter. Desde 2010 desenvolve aplicativos mobile para iOS e Android, e em 2014 passou a desenvolver também para Firefox OS. Para o desenvolvimento desses aplicativos, usou as seguintes linguagens e frameworks: Swift, Objective-C, HTML5, CSS3, JS e Apache Cordova. Também escreve artigos e faz palestras, além de ser voluntário do Mozzila, contribuindo para a comunidade.',
	    writerImg: 'assets/image/writers/jonathan-lamim.png',
	    bigImageUrl: 'assets/image/books/Marketingdeconteudo.png',
	    middleImageUrl: 'assets/image/books/Marketingdeconteudo.png',
	    smallImageUrl: 'assets/image/books/Marketingdeconteudo.png' 
    },
    {
        id: 49,
	    title: 'seo prático',
	    upon: 'Seu site na primeira página das buscas',
	    about: 'Marketing Digital',
	    section: 'business',
	    numPages: 165,
	    datePubli: '03/2015',
	    pricePrinted: 47.92,
	    priceEbook: 23.92,
	    pricePackage: 59.92,
	    description: 'Quando foi a última vez que você fez uma busca no Google? Provavelmente há poucos minutos atrás. Hoje em dia, para que seu negócio apareça, tenha destaque e ganhe novos clientes, não é mais necessário apenas ter um site. É preciso fazê-lo aparecer bem nas buscas. Justamente para isso, você precisa entender de Search Engine Optimization.',
	    writer: 'Adriano Almeida',
	    aboutWriter: 'Adriano Almeida, @adrianoalmeida7, é formado em Sistemas de Informação pela FIAP, começou sua carreira com Editoração Eletrônica e desenvolveu sistemas web em Java, Ruby on Rails, PHP e VB, além de diversos sites. Palestrou em eventos no Brasil e no exterior. Escreve para revistas técnicas. Atualmente, além de editor-chefe, é CTO da Casa do Código e responsável pelo SEO do site da editora.',
	    writerImg: 'assets/image/writers/adriano-almeida.png',
	    bigImageUrl: 'assets/image/books/SEOPratico.png',
	    middleImageUrl: 'assets/image/books/SEOPratico.png',
	    smallImageUrl: 'assets/image/books/SEOPratico.png'         
    },
    {
        id: 50,
	    title: 'métricas ágeis',
	    upon: 'Obtenha melhores resultados em sua equipe',
	    about: 'Agile',
	    section: 'business',
	    numPages: 262,
	    datePubli: '06/2017',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Em um meio onde queremos entregar melhores produtos de software para os clientes e usuários, torna-se muito relevante incluir em nosso repertório formas de monitorar a eficiência do processo de construção de software. Mas, afinal, por que você deve aprender sobre métricas e visualizações do processo de desenvolvimento software? Em um ambiente ágil, métricas podem ajudar a analisar a saúde do seu processo de construção, fornecendo dados históricos reais a partir dos quais é possível projetar cenários para as entregas, tendo um olhar mais concreto sobre o desenvolvimento e o atendimento de demandas.',
	    writer: 'Raphael Donaire Albino',
	    aboutWriter: 'Raphael Donaire Albino é doutorando e mestre em Administração de Empresas pela FEA-USP, formado em Sistemas de Informação, pela Unesp de Bauru, e com MBA em Gerenciamento de projetos, pela FGV. Profissional com mais de 10 anos de experiência na área de desenvolvimento de software, atua com programação, concepção de novos produtos, análise de requisitos e gestão de projetos e equipes.',
	    writerImg: 'assets/image/writers/raphael-donaire-albino.png',
	    bigImageUrl: 'assets/image/books/MetricasAgeis.png',
	    middleImageUrl: 'assets/image/books/MetricasAgeis.png',
	    smallImageUrl: 'assets/image/books/MetricasAgeis.png' 
    },
    {
        id: 51,
	    title: 'scrum 360',
	    upon: 'Um guia completo e prático de agilidade',
	    about: 'Agile',
	    section: 'business',
	    numPages: 189,
	    datePubli: '05/2015',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'Trabalhar com agilidade não é fácil. Fazer com que um time inteiro trabalhe de forma ágil, entregando resultados, produzindo de forma plena e sem impedimentos é muito mais difícil. Justamente para isso temos o Scrum, uma metodologia para gerenciamento de projetos que o torna produtivo.',
	    writer: 'Jorge Audy',
	    aboutWriter: 'Jorge Audy é escoteiro e agilista. Formou-se em 1986, foi concursado nos anos 80 e empresário nos 90. Também é Mestre em Administração na linha de pesquisa de Gestão da Informação e foi coordenador de desenvolvimento na ADP Brasil nos anos 2000 e no Grupo RBS até 2013, em equipes corporativas e de produtos digitais. Desde então, é consultor na DBServer. Praticante de métodos ágeis desde 2008, e Agile Coach desde 2011; e palestrante e participante ativo em eventos sobre métodos ágeis, equipes de alta performance e, mais especificamente, SCRUM.',
	    writerImg: 'assets/image/writers/jorge-audy.png',
	    bigImageUrl: 'assets/image/books/Scrum360.png',
	    middleImageUrl: 'assets/image/books/Scrum360.png',
	    smallImageUrl: 'assets/image/books/Scrum360.png'        
    },
    {
        id: 52,
        title: 'agile',
        upon: 'Desenvolvimento de software com entregas frequentes e foco no valor de negócio',
        about: 'Agile',
        section: 'business',
        numPages: 208,
        datePubli: '06/2013',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'As diversas metodologias ágeis que formam o tão falado "Agile" são hoje uma das maneiras mais eficientes de guiar um projeto do ínicio ao fim, sem complicações e mantendo o tempo inteiro o foco na entrega de valor para o cliente.',
        writer: 'André Faria Gomes',
        aboutWriter: 'André Faria Gomes é Sócio-Diretor de Produtos e Tecnologia na Bluesoft em São Paulo e Associated Trainer na Adaptworks. Bacharel em Sistemas de Informação pela FIAP, Black Belt em Lean Seis Sigma pela Fundação Vanzolini, e Management 3.0 Licensed Trainer. Escreve artigos para revistas e portais de TI, e mantém seu blog andrefaria.com. André é também tradutor, tendo traduzido o livro How to Change the World, de Jurgen Appelo, para português.',
        writerImg: 'assets/image/writers/andre-faria-gomes.png',
        bigImageUrl: 'assets/image/books/Agile.png',
        middleImageUrl: 'assets/image/books/Agile.png',
        smallImageUrl: 'assets/image/books/Agile.png'        
    },
    {
        id: 53,
	    title: 'lean game development',
	    upon: 'Desenvolvimento enxuto de jogos',
	    about: 'Agile',
	    section: 'business',
	    numPages: 202,
	    datePubli: '04/2017',
	    pricePrinted: 47.92,
	    priceEbook: 23.92,
	    pricePackage: 59.92,
	    description: 'Lean Game Development, ou Desenvolvimento Enxuto de Jogos, é um modelo de produção de jogos pensado de forma a atender todas as necessidades da indústria de jogos. Sendo orgânico a mudanças por meio de constantes reviews, ele oferece uma alternativa metodológica que pode nos auxiliar a eliminar desperdícios, reduzir bugs, obter resultados no menor tempo possível, fortalecer e empoderar o trabalho da equipe.',
	    writer: 'Julia Naomi Boeira',
	    aboutWriter: 'Julia Naomi Boeira é desenvolvedora de software na Thoughtworks Brasil e possui grande experiência no desenvolvimento de jogos, tendo idealizado o Lean Game Development. Atualmente, atua como divulgadora da engine Unity dentro da Thoughtworks principalmente em realidade aumentada.',
	    writerImg: 'assets/image/writers/julia-naomi-boeira.png',
	    bigImageUrl: 'assets/image/books/LeanGameDevelopment.png',
	    middleImageUrl: 'assets/image/books/LeanGameDevelopment.png',
	    smallImageUrl: 'assets/image/books/LeanGameDevelopment.png'        
    }
]