import { Db } from './casaDoCodigo-db'
import { Injectable } from '@angular/core'

@Injectable ({
    providedIn: 'root'
})

export class DbService {
    retriveAll(): Db[] {
        return DbLivros
    }
}

let DbLivros: Db[] = [
    {
        id: 1,
        title: 'html5 e css3',
        upon: 'Domine a web do futuro',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 228,
        datePubli: '05/2012',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'Crie páginas elegantes de forma simples! HTML e CSS, quando bem utilizados, podem ser o sucesso de um projeto e, com os novos recursos, muito do que antes era trabalhoso agora não é mais. Aprenda as melhores técnicas para escrever seu site por meio de exemplos práticos de funcionalidades úteis do cotidiano. Construa menus, aplique efeitos, estilize elementos visuais, melhore a semântica da sua página e muito mais!',
        writer: 'Natan Souza',
        aboutWriter: 'Lucas Mazza faz parte da equipe de desenvolvedores da Plataformatec, empresa de desenvolvimento de São Paulo, especializada em Ruby on Rails. Combinando a linguagem Ruby com HTML, CSS e JavaScript, ele busca desenvolver interfaces elegantes aliado a um código de qualidade, que satisfaça usuários e desenvolvedores envolvidos. No seu tempo livre, ele é aficionado por filmes, música, tecnologia e contribui com projetos open Sousce no GitHub. Seu usuário no GitHub é lucasmazza e está no Twitter em @lucasmazza.',
        writerImg: 'assets/image/writers/lucas-mazza.png',
        bigImageUrl: 'assets/image/books/HTML5eCSS3.png',
        middleImageUrl: 'assets/image/books/HTML5eCSS3.png',
        smallImageUrl: 'assets/image/books/HTML5eCSS3.png'
    }, 
    {
        id: 2,
        title: 'css3 eficiente',
        upon: 'Técnicas e ferramentas que fazem a diferença nos seus estilos',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 144,
        datePubli: '06/2015',
        pricePrinted: 52.15,
        priceEbook: 23.92,
        pricePackage: 62.99,
        description: 'Quando aprendemos a trabalhar com CSS, frequentemente nos pegamos perdidos em detalhes fundamentais que não nos são explicados. Por vezes, alguns desses detalhes passam despercebidos até pelo desenvolvedor front-end mais experiente. Mas como ir além do conhecimento básico do CSS e preparar o caminho para explorar tópicos mais avançados?',
        writer: 'Tárcio Zemel',
        aboutWriter: 'Tárcio Zemel trabalha com desenvolvimento web há 15 anos e atuar nessa área é uma das coisas que mais gosta de fazer. É sócio-fundador da empresa webfatorial, na qual trabalha em projetos web para grandes marcas do mundo todo.',
        bigImageUrl: 'assets/image/books/CSS3Eficiente.png',
        writerImg: 'assets/image/writers/tarcio-zemel.png',
        middleImageUrl: 'assets/image/books/CSS3Eficiente.png',
        smallImageUrl: 'assets/image/books/CSS3Eficiente.png'
    },
    {
        id: 3,
        title: 'sass',
        upon: 'Aprendendo pré-processadores CSS',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 166,
        datePubli: '08/2016',
        pricePrinted: 47.92,
        priceEbook: 29.95,
        pricePackage: 59.92,
        description: 'Na última década, surgiram os chamados processadores CSS, tecnologias que buscavam suprir as deficiências que encontrávamos na utilização de CSS comum, como repetição de código, ausência de funções, a difícil manutenção entre outros fatores. Sabemos que a única linguagem de estilos que os navegadores compreendem atualmente é o bom e velho CSS, daí a necessidade de um pré-processador que receba dados de entrada e os devolva compilados em um arquivo .css, facilitando o dia a dia do desenvolvimento front-end e trazendo grandes vantagens na implementação dos estilos.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Sass.png',
        middleImageUrl: 'assets/image/books/Sass.png',
        smallImageUrl: 'assets/image/books/Sass.png'
    },
    {
        id: 4,
        title: 'bootstrap 4',
        upon: 'Conheça a biblioteca front-end mais utilizada no mundo',
        about: 'HTML e CSS',
        section: 'front-end',
        numPages: 172,
        datePubli: '05/2018',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'Fazer um site elegante nunca foi tão fácil, mesmo para quem não sabe escrever uma linha de CSS e, muito menos, entende como harmonizar cores, balancear elementos e tipografia. O Bootstrap é, resumidamente, um grande arquivo CSS com uma excelente documentação, que possui dezenas e dezenas de componentes prontos. No começo, foi criado pelo Twitter para servir como um guia de estilos em CSS da empresa; hoje, é a biblioteca mais famosa e utilizada no mundo.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Bootstrap.png',
        middleImageUrl: 'assets/image/books/Bootstrap.png',
        smallImageUrl: 'assets/image/books/Bootstrap.png'
    },
    {
        id: 5,
        title: 'ecmascript 6',
        upon: 'Entre de cabeça no futuro do JavaScript',
        about: 'Javascript',
        section: 'front-end',
        numPages: 227,
        datePubli: '05/2018',
        pricePrinted: 55.92,
        priceEbook: 35.55,
        pricePackage: 67.92,
        description: 'Nos últimos anos, a linguagem JavaScript cresceu bastante na comunidade de desenvolvedores, tornando-se mais robusta, poderosa e sendo usada em uma infinidade de aplicações de alto nível, tanto no front-end quanto no back-end das aplicações. Ela é a tecnologia por trás de ferramentas, frameworks e bibliotecas consagradas no mercado, tais como: Angular, Ember, React, Backbone, jQuery, Grunt. A lista é enorme. Atualmente, é essencial que um profissional de TI tenha domínio desta tecnologia, tanto para aplicações web, aplicativos mobile e/ou desktop. É exatamente para isto que este livro foi escrito. Para que você seja capaz de entender todas as mudanças que vieram com o ECMAScript 6, aprimorar suas habilidades como desenvolvedor e se destacar no mercado de trabalho que hoje é tão concorrido.',
        writer: 'Diego Martins de Pinho',
        aboutWriter: 'Bacharel em Ciência da Computação pela PUC-SP e MBA em Gestão da Tecnologia da Informação pela FIAP. É aficionado não somente por tecnologia, mas também por empreendedorismo e gestão de negócios. Trabalha com desenvolvimento web desde 2013 e sempre busca tempo para continuar aprendendo e para disseminar o conhecimento.',
        writerImg: 'assets/image/writers/diego-martins.png',
        bigImageUrl: 'assets/image/books/ECMAScript6.png',
        middleImageUrl: 'assets/image/books/ECMAScript6.png',
        smallImageUrl: 'assets/image/books/ECMAScript6.png'
    },
    {
        id: 6,
        title: 'angular 11 e firebase',
        upon: 'Construindo uma aplicação integrada com a plataforma do Google',
        about: 'Javascript',
        section: 'front-end',
        numPages: 163,
        datePubli: '03/2021',
        pricePrinted: 47.92,
        priceEbook: 33.55,
        pricePackage: 60.55,
        description: 'No desenvolvimento de aplicações web e mobile, há disponível uma quantidade expressiva de linguagens, frameworks e ferramentas. Nessa imensidão, é comum se questionar ou até ter inseguranças sobre qual o melhor caminho para a construção neste segmento. O Angular é uma plataforma que facilita a construção de aplicativos, combinando templates, injeção de dependências, tudo integrado às melhores práticas de desenvolvimento.',
        writer: 'Kheronn Khennedy Machado',
        aboutWriter: 'Kheronn Khennedy Machado é professor da rede pública estadual do Paraná. Atua na formação de professores para uso de tecnologia em sala de aula. Desenvolve desde 2007 aplicações para web e mobile, tendo recentemente focado em soluções que utilizam Javascript. Possui Mestrado em Informática pela UFPR e Graduação em Processamento de Dados pela Fatec Ourinhos.',
        writerImg: 'assets/image/writers/kheronn-khennedy.png',
        bigImageUrl: 'assets/image/books/AngularEFirebase.png',
        middleImageUrl: 'assets/image/books/AngularEFirebase.png',
        smallImageUrl: 'assets/image/books/AngularEFirebase.png'
    },
    {
        id: 7,
        title: 'guia prático de typescript',
        upon: 'Melhore suas aplicações JavaScript',
        about: 'Javascript',
        section: 'front-end',
        numPages: 178,
        datePubli: '07/2021',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.84,
        description: 'Desenvolvido e mantido pela Microsoft, o TypeScript é um pré-processador open source de códigos JavaScript que auxilia na escrita de códigos, desde os mais simples até os mais complexos, utilizando tipagem de dados e os princípios da Orientação a Objetos para o desenvolvimento de aplicações front-end, back-end e mobile.',
        writer: 'Thiago da Silva Adriano',
        aboutWriter: 'Thiago da Silva Adriano é Microsoft (MVP) e atualmente trabalha como Engenheiro de Software. Nesses últimos anos, focou nas tecnologias criadas pela Microsoft, mas sempre esteve antenado para as novas tecnologias que estão surgindo no mercado. Em um breve resumo, é uma pessoa apaixonada pelo que faz, tem a sua profissão como hobby.',
        writerImg: 'assets/image/writers/thiago-silva.png',
        bigImageUrl: 'assets/image/books/GuiaTypescript.png',
        middleImageUrl: 'assets/image/books/GuiaTypescript.png',
        smallImageUrl: 'assets/image/books/GuiaTypescript.png'
    },
    {
        id: 8,
        title: 'vue.js',
        upon: 'construa aplicações incríveis',
        about: 'Javascript',
        section: 'front-end',
        numPages: 174,
        datePubli: '04/2017',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'O modo como desenvolvemos código front-end mudou muito ao longo dos últimos anos. Mais do que dar as ferramentas necessárias para desenvolver, os frameworks de componentes reativos para interfaces web modernas vieram nos ajudar com padrões e reaproveitamento de código. Vue.js, ou simplesmente Vue, é uma biblioteca moderna de desenvolvimento front-end, uma lib JavaScript para componentes reativos para web. Ele ganhou muita visibilidade no mercado após ser adotado como padrão pelo Laravel, tendo a possibilidade de ser utilizado em qualquer projeto que possua front-end, independente da linguagem de programação escolhida.',
        writer: 'Caio Incau',
        aboutWriter: 'Caio Incau estudou Sistemas de Informação e trabalha com desenvolvimento de software na Caelum desde seus 18 anos. Durante sua estadia no mercado de TI, teve a oportunidade de trabalhar com Java, Ruby, JavaScript e Objective-C.',
        writerImg: 'assets/image/writers/caio-incau.png',
        bigImageUrl: 'assets/image/books/VueJS.png',
        middleImageUrl: 'assets/image/books/VueJS.png',
        smallImageUrl: 'assets/image/books/VueJS.png'
    },
    {
        id: 9,
        title: 'acessibilidade na web',
        upon: 'Boas práticas para construir sites e aplicações acessíveis',
        about: 'Outros',
        section: 'front-end',
        numPages: 246,
        datePubli: '04/2020',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 71.92,
        description: 'Acessibilidade na Web consiste na eliminação de barreiras de acesso em páginas e aplicações digitais para que pessoas com deficiência tenham autonomia na rede. Na verdade, acessibilidade na web beneficia todas as pessoas. Em algum momento da vida todos podem precisar de acessibilidade, seja devido a uma limitação temporária ou permanente. Quando não levamos em consideração o acesso de pessoas com deficiência, estamos tirando o direito de uma pessoa de navegar, interagir ou consumir produtos e serviços na rede. Empatia é o fator principal para que as aplicações que desenvolvemos sejam inclusivas.',
        writer: 'Reinaldo Ferraz',
        aboutWriter: 'Formado em desenho e computação gráfica e pós-graduado em design de hipermídia pela Universidade Anhembi Morumbi em São Paulo. Trabalha com desenvolvimento web desde 1998. Coordena as iniciativas de acessibilidade na Web do NIC.br e projetos relacionados a Open Web Platform, Digital Publishing e Web das Coisas. Representante do NIC.br em grupos de trabalho do W3C internacional em Acessibilidade na Web, Digital Publishing e Web das Coisas. Apaixonado por acessibilidade, usabilidade, padrões web, HTML, CSS e café sem açúcar.',
        writerImg: 'assets/image/writers/reinaldo-ferraz.png',
        bigImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        middleImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        smallImageUrl: 'assets/image/books/Acessibilidade-na-Web.png'
    },
    {
        id: 10,
        title: 'progressive web apps',
        upon: 'Construa aplicações progressivas com React',
        about: 'Outros',
        section: 'front-end',
        numPages: 443,
        datePubli: '04/2018',
        pricePrinted: 71.92,
        priceEbook: 31.92,
        pricePackage: 83.92,
        description: 'PWA é um acrônimo para Progressive Web Apps, ou Aplicações Web Progressivas. Com o passar dos dias, mais e mais sistemas mobile e navegadores suportam os requisitos PWA, com uma expectativa real de que a Progressive Enhancement, ou melhoria progressiva, deixe de apenas pertencer às boas práticas de desenvolvimento web e passe a ser norma. Desenvolver com melhoria progressiva é um paradigma em que a aplicação deverá estar disponível para todos, sejam usuários de microcomputadores ou smartphones, com browsers atualizados ou obsoletos, com conexão à internet ou não, propiciando uma experiência de acesso contínuo sem nenhum tipo de restrição tecnológica.',
        writer: 'Guilherme Pontes',
        aboutWriter: 'Um profissional de TI, que adora TI, principalmente quando se trata de minúcias relacionadas a Linux, Node.JS, Python, MySQL, MongoDB, apps mobile ou progressivas, e muito JavaScript. http://lgapontes.com/',
        writerImg: 'assets/image/writers/guilherme-pontes.png',
        bigImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        middleImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        smallImageUrl: 'assets/image/books/ProgressiveWebApps.png'
    },
    {
        id: 11,
        title: 'introdução à web semântica',
        upon: 'A inteligência da informação',
        about: 'Outros',
        section: 'front-end',
        numPages: 170,
        datePubli: '09/2012',
        pricePrinted: 47.92,
        priceEbook: 23.92,
        pricePackage: 59.92,
        description: 'Por que precisamos da Web Semântica? A Web de hoje não é suficiente? Estamos caminhando para uma Web com dados cada vez mais relacionados e abertos. A Web Semântica é uma extensão da nossa web atual, em que nós não vamos apenas ler e produzir conteúdo, mas usar as máquinas para relacionar e reutilizar essas informações da melhor maneira possível. Ela se baseia na ideia de que o conteúdo deve ter uma descrição digital, padronizada por vocabulários, que provê meios para as máquinas entenderem do que aquilo se trata, de modo que os computadores possam interpretar, gerar e distribuir conteúdo útil, de acordo com as necessidades dos usuários.',
        writer: 'Diego Eis',
        aboutWriter: 'Diego Eis é apaixonado e sempre trabalhou com internet. Em 2003, fundou o Tableless, onde escreve com vários outros autores sobre desenvolvimento web e front-end. Já palestrou em vários eventos nacionais de tecnologia, faculdades e empresas por todo o país, passou seis anos de sua carreira profissional dirigindo a própria empresa, fazendo projetos para companhias como Globo.com, Itaú, Nokia, Samsung e outras. É autor do livro Guia Front-End, destinado aos iniciantes da área. Atualmente, é gestor de produtos na Easynvest.',
        writerImg: 'assets/image/writers/diego-eis.png',
        bigImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        middleImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        smallImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png'
    },
    {
        id: 12,
        title: 'aprofundando em flutter',
        upon: 'Desenvolva aplicações Dart com Widgets',
        about: 'Outros',
        section: 'front-end',
        numPages: 319,
        datePubli: '06/2021',
        pricePrinted: 63.92,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'Flutter é um framework do Google que tem conquistado o coração de muitas pessoas no desenvolvimento de aplicativos cross-platform, tanto para dispositivos móveis, como com versões estáveis para desenvolvimento web, desktop e PWA. Sua estrutura baseada em widgets, que são componentes visuais ou não, com propriedades e eventos customizáveis através da linguagem Dart, abre um leque infinito de possibilidades para criar aplicações completas. Se você já conhece Flutter e quer dar o próximo passo nessa relação, este é o caminho.',
        writer: 'Everton Coimbra de Araújo',
        aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
        writerImg: 'assets/image/writers/everton-coimbra-de-araujo.png',
        bigImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        middleImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        smallImageUrl: 'assets/image/books/Aprofundandoemflutter.png'
    },
    {
        id: 13,
        title: 'Lógica de programação com Portugol',
        upon: 'Mais de 80 exemplos, 55 exercícios com gabarito e vídeos complementares',
        about: 'Lógica',
        section: 'programacao',
        numPages: 275,
        datePubli: '02/2022',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'O primeiro passo no mundo do desenvolvimento de aplicativos, softwares e sistemas informatizados envolve lógica de programação. É conhecer conceitos fundamentais sobre o funcionamento de comandos para passarmos para o computador o que ele deve fazer e qual a sequência correta do que deve ser feito. Isso se torna mais palpável com uma linguagem mais próxima à que já dominamos: o português. Com foco no aprendizado, Portugol é uma pseudo-linguagem de programação que oferece uma abordagem acessível para você aprender a montar seus primeiros algoritmos com lógica de programação.',
        writer: 'Joice Barbosa Mendes',
        aboutWriter: 'Joice Barbosa Mendes Bacharelada em Ciência da Computação (UNIFEI-MG) em 2009. Concluiu o Mestrado em Ciência e Tecnologia da Computação (UNIFEI-MG) em 2012, com foco em Sistemas Tutores Inteligentes. Possui Formação Pedagógica para Educação Profissional de Nível Médio (IFSP-SP). Iniciou sua carreira como docente em 2012, atuando em disciplinas de programação do ensino superior para cursos de engenharia e Sistemas de Informação. Em 2016 passou a atuar em disciplinas de lógica de programação e orientação a objetos no IFSP, para cursos técnicos e de graduação.',
        writerImg: 'assets/image/writers/joice-barbosa.png',
        bigImageUrl: 'assets/image/books/logica-programacao.png',
        middleImageUrl: 'assets/image/books/logica-programacao.png',
        smallImageUrl: 'assets/image/books/logica-programacao.png'
    },
    {
        id: 14,
        title: 'App Inventor',
        upon: 'Seus primeiros aplicativos Android',
        about: 'Lógica',
        section: 'programacao',
        numPages: 305,
        datePubli: '11/2021',
        pricePrinted: 63.91,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'O App Inventor 2 é uma ferramenta inovadora, desenvolvida pelo Google e mantida hoje pelo Instituto de Tecnologia de Massachusetts (MIT). Com ela, é possível criar aplicativos para dispositivos móveis Android, por meio de uma linguagem visual, sem precisar decorar ou escrever códigos de linguagem de programação. Com um simples arrastar e inserir blocos para a área de programação, em uma interface intuitiva, é uma excelente ferramenta de aprendizado que permite que os recém-chegados à programação de computador criem aplicativos completos.',
        writer: 'Nelson Fabbri Gerbelli',
        aboutWriter: 'Nelson Fabbri Gerbelli é Tecnólogo em Processamento de Dados pela faculdade FAINAM, pós-graduado em Análise de Sistemas pela faculdade ESAN. Pedagogo e possui licenciatura plena em Informática. É professor em cursos de TI no Centro Estadual de Educação Tecnológica Paula Souza do Estado de São Paulo nas ETECs, atuando principalmente nas seguintes disciplinas: Tecnologia para mobilidade, técnicas de programação para internet e desenvolvimento de softwares com o Visual Studio.Net.',
        writerImg: 'assets/image/writers/nelson-fabbri.png',
        bigImageUrl: 'assets/image/books/AppInventor.png',
        middleImageUrl: 'assets/image/books/AppInventor.png',
        smallImageUrl: 'assets/image/books/AppInventor.png'
    },
    {
        id: 15,
        title: 'Introdução à programação em C',
        upon: 'Os primeiros passos de um desenvolvedor',
        about: 'Lógica',
        section: 'programacao',
        numPages: 290,
        datePubli: '08/2015',
        pricePrinted: 63.92,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'Você já programou alguma vez na vida? Pois então, prepare-se: sua vida vai mudar. Ensinar a máquina a fazer o que quer que ela faça é extremamente divertido. C é uma ótima linguagem para quem quer aprender programação: é bastante popular, poderosa, e nos dá diferentes níveis de abstração.',
        writer: 'Mauricio Aniche',
        aboutWriter: 'Maurício é instrutor e desenvolvedor da Caelum, possui mais de 9 anos de experiência de desenvolvimento de softwares, tendo participado de projetos para grandes empresas nacionais e internacionais. Mauricio é também mestre em Ciência da Computação pela Universidade de São Paulo (USP) onde pesquisa sobre TDD e sua influência no design de sistemas orientados a objetos. Atualmente é aluno de doutorado pelo mesmo instituto. Palestrante em eventos nacionais e internacionais, com destaque para sua apresentação no 1o Workshop Internacional sobre Test-Driven Development, localizado em Paris, no ano de 2010, Agile Brazil 2010, 2011 e 2012, e QCON SP 2010 e 2012. Mauricio gosta de discutir sobre TDD, melhores práticas e princípios de orientação a objetos, métodos ágeis de desenvolvimento de software e linguagens de programação. Está no Twitter como @mauricioaniche .',
        writerImg: 'assets/image/writers/mauricio-aniche.png',
        bigImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png',
        middleImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png',
        smallImageUrl: 'assets/image/books/IntroducaoaprogramacaoemC.png'
    },
    {
        id: 16,
	    title: 'Lógica de Programação',
	    upon: 'Crie seus primeiros programas usando Javascript e HTML',
	    about: 'Lógica',
	    section: 'programacao',
	    numPages: 180,
	    datePubli: '05/2012',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'Aprenda a programar agora! Este livro apresenta uma abordagem totalmente prática. Uma didática pensada no iniciante, com a qual os conceitos são apresentados com motivações práticas, através do surgimento da necessidade para depois mostrar a solução.',
	    writer: 'Paulo Silveira',
	    aboutWriter: 'Paulo Silveira, @paulo_caelum, é bacharel e mestre em Ciência da Computação pela USP, possui mais de 10 anos de experiência com desenvolvimento, passando pela Alemanha e pelo IBOPE. Coordena os cursos da Caelum nos cursos de verão da USP. Um dos fundadores do GUJ.com.br e é editor técnico da revista Mundo Java.',
	    writerImg: 'assets/image/writers/paulo-silveira.png',
	    bigImageUrl: 'assets/image/books/LogicadeProgramacao.png',
	    middleImageUrl: 'assets/image/books/LogicadeProgramacao.png',
	    smallImageUrl: 'assets/image/books/LogicadeProgramacao.png'
    },
    {
        id: 17,
        title: 'Java 9',
        upon: 'Interativo, reativo e modularizado',
        about: 'Java',
        section: 'programacao',
        numPages: 273,
        datePubli: '09/2017',
        pricePrinted: 55.92,
        priceEbook: 23.92,
        pricePackage: 67.92,
        description: 'Com mais de 20 anos de plataforma, um novo Java surge com novidades importantes. O destaque especial vai para o sistema de módulos, o Jigsaw, e a modularização do próprio JDK. A linguagem também ficou interativa, com a adição de uma ferramenta de REPL (Read-Eval-Print Loop), e mais reativa, com uma API de fluxos inteiramente dedicada aos famosos Reactive Streams',
        writer: 'Rodrigo Turini',
        aboutWriter: 'Rodrigo Turini é Bacharel em Ciência da Computação e líder técnico na Alura, a plataforma de cursos online do Grupo Caelum. Desenvolve em diferentes linguagens, mas tem um envolvimento muito forte com o Java, sendo membro ativo da JCP e de expert groups do JavaEE. Turini participa ativamente da comunidade em blogs, fóruns, listas de discussões e também em eventos nacionais e internacionais. É um dos líderes de desenvolvimento do VRaptor, e contribui para diversos outros projetos e manifestos open source. Gosta de estudar continuamente as melhores práticas da orientação a objetos, programação funcional e reativa.',
        writerImg: 'assets/image/writers/rodrigo-turini.png',
        bigImageUrl: 'assets/image/books/Java9.png',
        middleImageUrl: 'assets/image/books/Java9.png',
        smallImageUrl: 'assets/image/books/Java9.png'
    }, {
       id: 18,
       title: 'Apache Kafka e Spring Boot',
       upon: 'Comunicação assíncrona entre microsserviços',
       about: 'Java',
       section: 'programacao',
       numPages: 189,
       datePubli: '01/2022',
       pricePrinted: 55.92,
       priceEbook: 31.92,
       pricePackage: 59.92,
       description: 'Pensar em comunicação assíncrona entre microsserviços é um caminho interessante quando a aplicação demanda serviços que podem demorar para responder. Para evitar problemas de timeouts e retentativas, utilizam-se filas ou tópicos, aos quais um processo adiciona uma mensagem informando o processamento a ser feito e outro a recebe quando estiver disponível e executa. O Kafka é atualmente um dos principais sistemas para a implementação de processamento assíncrono. Além de disponibilizar os tópicos para a produção e consumo de mensagens, suas diversas funcionalidades facilitam a implementação de nossas aplicações, com a distribuição e o balanceamento de carga entre os consumidores e o processamento de fluxos de dados.',
       writer: 'Eduardo Felipe Zambom Santana',
       aboutWriter: 'Eduardo Felipe Zambom Santana tem mais de 15 anos de experiência em Engenharia de Software. Trabalha principalmente como Java, já tendo trabalhado com os principais frameworks da linguagem como Struts, JSF e Spring. Também tem bastante experiência em outras linguagens como Python e Erlang. Formou-se em Ciência da Computação na UFSCar (2007), fez mestrado também na UFSCar (2010) e doutorado na USP (2019) trabalhando na área de sistemas distribuídos.',
       writerImg: 'assets/image/writers/eduardo-felipe.png',
       bigImageUrl: 'assets/image/books/Apache-Kafka.png',
       middleImageUrl: 'assets/image/books/Apache-Kafka.png',
       smallImageUrl: 'assets/image/books/Apache-Kafka.png' 
    }, 
    {
        id: 19,
	    title: 'Back-end Java',
	    upon: 'Microsserviços, Spring Boot e Kubernetes',
	    about: 'Java',
	    section: 'programacao',
	    numPages: 143,
	    datePubli: '03/2021',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'A arquitetura dos sistemas de software vem sofrendo diversas revoluções nos últimos anos, desde os grandes monólitos até os microsserviços. Atualmente, para a plataforma Java, o framework mais utilizado para desenvolver microsserviços é o Spring Boot, que facilita a configuração e o uso de bibliotecas necessárias. Mas para executar uma aplicação inteira, tanto em um ambiente local quanto de produção, é necessário rodar e configurar todos os serviços e permitir que eles se comuniquem. Hoje é essencial que a pessoa desenvolvedora back-end conheça, além da linguagem de programação, algumas dessas ferramentas para a execução da aplicação em um ambiente de produção. É esse o objetivo dos contêineres Docker e do Kubernetes.',
	    writer: 'Eduardo Felipe Zambom Santana',
	    aboutWriter: 'Eduardo Felipe Zambom Santana tem mais de 15 anos de experiência em Engenharia de Software. Trabalha principalmente como Java, já tendo trabalhado com os principais frameworks da linguagem como Struts, JSF e Spring. Também tem bastante experiência em outras linguagens como Python e Erlang. Formou-se em Ciência da Computação na UFSCar (2007), fez mestrado também na UFSCar (2010) e doutorado na USP (2019) trabalhando na área de sistemas distribuídos.',
	    writerImg: 'assets/image/writers/eduardo-felipe.png',
	    bigImageUrl: 'assets/image/books/Back-EndJava.png',
	    middleImageUrl: 'assets/image/books/Back-EndJava.png',
	    smallImageUrl: 'assets/image/books/Back-EndJava.png'
    },
    {
        id: 20,
	    title: 'Design Patterns com Java',
	    upon: 'Projeto orientado a objetos guiado por padrões',
	    about: 'Java',
	    section: 'programacao',
	    numPages: 334,
	    datePubli: '11/2012',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Não é trivial compreender bem os design patterns. Entender quando aplicá-los é algo que qualquer desenvolvedor deve saber. Nesse livro, você aprenderá com exemplos práticos e bem contextualizados como aplicar os padrões e em quais situações um é mais indicado que o outro. Diferencie as características particulares de cada padrão, crie aplicações que usam o melhor da orientação a objetos em seu favor e desenvolva aplicações que você conseguirá manter para sempre!',
	    writer: 'Eduardo Guerra',
	    aboutWriter: 'Eduardo Guerra é desenvolvedor de frameworks, editor-chefe da revista MundoJ e pesquisador do Instituto Nacional de Pesquisas Espaciais (INPE). Foi professor do Instituto Tecnológico de Aeronáutica (ITA), onde concluiu sua graduação, mestrado e doutorado. Suas pesquisas se concentram nas áreas de design, arquitetura e teste de software. Possui diversas certificações da plataforma Java e experiência como arquiteto de software. Participa de projetos de frameworks open-source, como SwingBean, Esfinge e ClassMock. Ele acredita que um bom software se faz mais com criatividade do que com código e vive em busca de melhores formas para seu desenvolvimento. Está no Twitter como @emguerra.',
	    writerImg: 'assets/image/writers/eduardo-guerra.png',
	    bigImageUrl: 'assets/image/books/DesignPatternsJava.png',
	    middleImageUrl: 'assets/image/books/DesignPatternsJava.png',
	    smallImageUrl: 'assets/image/books/DesignPatternsJava.png'
    }, 
    {
        id: 21,
	    title: 'Python',
	    upon: 'Escreva seus primeiros programas',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 269,
	    datePubli: '09/2015',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Python é a principal linguagem de programação utilizada no Google e repleta de funcionalidades interessantes. Neste livro, Felipe Cruz vai introduzi-lo ao Python 3, a versão mais atual, mostrando seu funcionamento, sintaxe, manipulação de arquivos, tratamento de exceções, estruturas de dados, a biblioteca padrão e tudo o que você precisa saber para começar a programar nessa linguagem.',
	    writer: 'Felipe Cruz',
	    aboutWriter: 'Felipe Cruz é desenvolvedor de software há 10 anos. Trabalhou no mercado corporativo e de startups e recentemente atua como Cientista de Dados, área onde reencontrou sua paixão pela construção de software. Mestrando em Computação pela PUC-Rio, também estuda Aprendizado de Máquinas e atualmente busca novas formas de resolver o problema da recomendação e o aprendizado não supervisionado de atributos. Pythonista há 6 anos, palestrante e participante de diversas Python Brasil, sempre buscou compartilhar conhecimento e aprender cada vez mais sobre a linguagem e o ecossistema ao longo desses anos.',
	    writerImg: 'assets/image/writers/felipe-cruz.png',
	    bigImageUrl: 'assets/image/books/Python.png',
	    middleImageUrl: 'assets/image/books/Python.png',
	    smallImageUrl: 'assets/image/books/Python.png'
    },
    {
        id: 22,
	    title: 'Trilhas Python',
	    upon: 'Programação multiparadigma e desenvolvimento Web com Flask',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 277,
	    datePubli: '06/2018',
	    pricePrinted: 55.92,
	    priceEbook: 31.91,
	    pricePackage: 67.92,
	    description: 'Neste livro, Eduardo Pereira apresenta tópicos de programação em Python que vão do básico ao avançado. Você verá desde estrutura de dados, funções e decoradores e criará um Jogo da Velha seguindo o paradigma de Programação Estruturada, aprimorando-o com Orientação a Objetos. Em seguida, são abordados tópicos mais avançados da linguagem, como compreensões e geradores, que são fundamentais para a Programação Funcional em Python. Por último, você aplicará o conhecimento de programação Python para o desenvolvimento Web, criando uma aplicação de streaming de música, com o framework Flask, juntamente com uma Database Abstraction Layer (PyDAL) para a integração da aplicação com banco de dados.',
	    writer: 'Eduardo Pereira',
	    aboutWriter: 'Eduardo S. Pereira é mestre e doutor em Astrofísica, pelo Instituto Nacional de Pesquisas Espaciais (INPE). Possui graduação em Física pela Universidade Federal de São João Del-Rei. Também realizou pós-doutorado em Astrofísica, pelo INPE, e em Astronomia Observacional/Computacional, pela Universidade de São Paulo (USP). Atua principalmente nos seguintes temas de pesquisa: cosmologia, ondas gravitacionais, astrofísica computacional, processamento de imagens e inteligência artificial. Atualmente, é professor do curso de Ciência da Computação da Faculdade Anhanguera, e Tutor no curso de física na Universidade Virtual de São Paulo (UNIVESP). Trabalha com Python há mais de 6 anos.',
	    writerImg: 'assets/image/writers/eduardo-pereira.png',
	    bigImageUrl: 'assets/image/books/TrilhasPython.png',
	    middleImageUrl: 'assets/image/books/TrilhasPython.png',
	    smallImageUrl: 'assets/image/books/TrilhasPython.png'
    },
    {
        id: 23,
	    title: 'Flask de A - Z',
	    upon: 'Crie aplicações web mais completas e robustas em Python',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 223,
	    datePubli: '10/2019',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Flask é um dos melhores frameworks para se trabalhar no Python atualmente. Por ser uma ferramenta robusta e completa, ela permite que a aplicação Web seja construída de forma a atender às necessidades de seu usuário final, ao mesmo tempo em que flexibiliza o fluxo de desenvolvimento de uma equipe. Flask interage de forma excelente com SQLAlchemy, uma biblioteca ORM muito interessante e completa, que nos permite trabalhar com diversos bancos de dados relacionais dentro do Python com segurança, e isso trará muitas vantagens para nossos estudos.',
	    writer: 'Tiago Silva',
	    aboutWriter: 'Tiago Silva é graduado em Análise e Desenvolvimento de Sistemas pelas Faculdades Integradas Simonsen, professor na área de Tecnologia há mais de 6 anos, atualmente trabalha como cientista de dados onde desenvolve sistemas e scripts em Python focados em processamento de um alto volume de dados. Especialista em Python, Google Maps e Adobe Muse é fundador do Canal Digital Cursos, onde existem cursos inteiramente online focados em ajudar pessoas a entrarem para o mercado de trabalho.',
	    writerImg: 'assets/image/writers/tiago-silva.png',
	    bigImageUrl: 'assets/image/books/FlaskAZ.png',
	    middleImageUrl: 'assets/image/books/FlaskAZ.png',
	    smallImageUrl: 'assets/image/books/FlaskAZ.png'
    },
    {
        id: 24,
	    title: 'Django de A - Z',
	    upon: 'Crie aplicações web rápidas, seguras e escaláveis com Python',
	    about: 'Python',
	    section: 'programacao',
	    numPages: 320,
	    datePubli: '04/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Considerado o framework mais popular no Python, Django é uma ferramenta completa e robusta, que nos permite criar uma aplicação web de forma rápida e consistente. Se você quer avançar no mercado de Python ou ingressar nele, ao dominar Django você terá as habilidades necessárias para construir enormes aplicações que poderão ser utilizadas por pequenas, médias e grandes corporações.',
	    writer: 'Tiago Silva',
	    aboutWriter: 'Tiago Silva é graduado em Análise e Desenvolvimento de Sistemas pelas Faculdades Integradas Simonsen, professor na área de Tecnologia há mais de 6 anos, atualmente trabalha como cientista de dados onde desenvolve sistemas e scripts em Python focados em processamento de um alto volume de dados. Especialista em Python, Google Maps e Adobe Muse é fundador do Canal Digital Cursos, onde existem cursos inteiramente online focados em ajudar pessoas a entrarem para o mercado de trabalho.',
	    writerImg: 'assets/image/writers/tiago-silva.png',
	    bigImageUrl: 'assets/image/books/DjangoAZ.png',
	    middleImageUrl: 'assets/image/books/DjangoAZ.png',
	    smallImageUrl: 'assets/image/books/DjangoAZ.png'
    },
    {
        id: 25,
	    title: 'Ionic 6',
	    upon: 'Desenvolvimento multiplataforma para dispositivos móveis',
	    about: 'iOS',
	    section: 'mobile',
	    numPages: 358,
	    datePubli: '01/2022',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Everton Coimbra de Araújo aborda o Ionic 6, junto de frameworks específicos, como o Capacitor, que possibilita a transformação de uma aplicação Ionic em uma aplicação híbrida. Você vai aprender na prática com um projeto de exemplo que pode ser executado, com recursos nativos, nos sistemas operacionais iOS e Android, testando-o em emuladores e em dispositivos físicos. Dentre as funcionalidades exploradas, estão: persistência de dados, tanto local como por meio do SQLite e Firestore, criação da interface com o usuário, navegação entre páginas, operações CRUD, e ainda, o uso de recursos como câmera e álbum de fotografia.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/Ionic-6.png',
	    middleImageUrl: 'assets/image/books/Ionic-6.png',
	    smallImageUrl: 'assets/image/books/Ionic-6.png'
    },
    {
        id: 26,
	    title: 'Xamarin Forms e MVVM',
	    upon: 'Persistência local com Entity Framework Core',
	    about: 'iOS',
	    section: 'mobile',
	    numPages: 470,
	    datePubli: '08/2021',
	    pricePrinted: 71.92,
	    priceEbook: 23.92,
	    pricePackage: 83.92,
	    description: 'Neste livro, Everton Coimbra demonstra na prática como criar uma aplicação para iOS e Android com Xamarin e Xamarin Forms, utilizando a linguagem C#. Você vai desenvolver um projeto de exemplo que lidará com cadastro, imagens e base de dados, aplicando o modelo MVVM (Model, View, ViewModel). Para o acesso à base de dados, será feito uso do Entity Framework Core, API da Microsoft para persistência de objetos em um paradigma relacional. O autor ainda complementa o material com a implementação de serviços REST em um servidor Web, para serem consumidos em sua aplicação Xamarin. Tudo isso em uma arquitetura bem elaborada e flexível, que você poderá comprovar.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/XamarinFormseMVVM.png',
	    middleImageUrl: 'assets/image/books/XamarinFormseMVVM.png',
	    smallImageUrl: 'assets/image/books/XamarinFormseMVVM.png'
    },
    {
        id: 27,
	    title: 'Kotlin com Android',
	    upon: 'Crie aplicativos de maneira fácil e divertida',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 346,
	    datePubli: '07/2018',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Kassiano Resende apresenta a linguagem Kotlin tanto para quem já conhece Java ou não, com uma didática prática e divertida. Você verá todos os passos necessários para construir e publicar na Play Store aplicações mobile em Kotlin, no ambiente de desenvolvimento Android Studio. O escopo das aplicações apresentadas no livro vai além das funcionalidades da linguagem, com a utilização de banco de dados, acesso a APIs REST e funcionalidades dos smartphones, como notificações, acesso à galeria de imagens, câmera e localização através de GPS.',
	    writer: 'Kassiano Resende',
	    aboutWriter: 'Kassiano Resende trabalha com desenvolvimento de software desde 2008, e desde então teve sua carreira voltada a plataformas web e mobile. Atualmente, é professor do SENAI-SP, ministrando disciplinas de programação para dispositivos móveis e projetos de software. Apaixonado por open source, está sempre estudando novas tecnologias.',
	    writerImg: 'assets/image/writers/kassiano-resende.png',
	    bigImageUrl: 'assets/image/books/KotlincomAndroid.png',
	    middleImageUrl: 'assets/image/books/KotlincomAndroid.png',
	    smallImageUrl: 'assets/image/books/KotlincomAndroid.png'
    },
    {
        id: 28,
	    title: 'App Inventor',
	    upon: 'Seus primeiros aplicativos Android',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 305,
	    datePubli: '11/2021',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Nelson e Valéria Gerbelli têm como objetivo proporcionar aos estudantes, educadores e entusiastas por tecnologia o primeiro passo no mundo da programação para dispositivos móveis por meio do App Inventor. Após ser apresentado ao ambiente, você aprenderá na prática a desenvolver alguns aplicativos do zero, partindo de alguns cálculos, até chegar a resultados mais complexos, com um recurso de localização de GPS, tradução de idioma e desenvolvendo um projeto final completo. Dentre as funcionalidades, estão o compartilhamento com outros aplicativos como o WhatsApp, a conexão a um banco de dados em MySQL, e a disponibilização do aplicativo na loja do Google Play Store.',
	    writer: 'Nelson Fabbri Gerbelli',
	    aboutWriter: 'Nelson Fabbri Gerbelli é Tecnólogo em Processamento de Dados pela faculdade FAINAM, pós-graduado em Análise de Sistemas pela faculdade ESAN. Pedagogo e possui licenciatura plena em Informática. É professor em cursos de TI no Centro Estadual de Educação Tecnológica Paula Souza do Estado de São Paulo nas ETECs, atuando principalmente nas seguintes disciplinas: Tecnologia para mobilidade, técnicas de programação para internet e desenvolvimento de softwares com o Visual Studio.Net.',
	    writerImg: 'assets/image/writers/nelson-fabbri.png',
	    bigImageUrl: 'assets/image/books/AppInventor.png',
	    middleImageUrl: 'assets/image/books/AppInventor.png',
	    smallImageUrl: 'assets/image/books/AppInventor.png'
    },
    {
        id: 29,
	    title: 'Entrega contínua em Android',
	    upon: 'Como automatizar a distribuição de apps',
	    about: 'Android',
	    section: 'mobile',
	    numPages: 190,
	    datePubli: '09/2016',
	    pricePrinted: 47.92,
	    priceEbook: 23.92,
	    pricePackage: 59.92,
	    description: 'Neste livro, Roger Silva vem preencher esta lacuna, explicando como automatizar a distribuição do app para o Google Play, como executar testes automatizados sobre as suas funcionalidades e disponibilizá-lo para a equipe de testes em vários dispositivos. Você verá como tratar todos esses requisitos para que, quando um desenvolvedor comitar seu código-fonte para um repositório de código remoto, uma bateria de testes automatizados seja executada, acompanhada por uma análise de cobertura de código-fonte, verificações de regras de negócios e, por fim, chegando até a etapa de distribuição automatizada do app para o Google Play.',
	    writer: 'Roger Silva',
	    aboutWriter: 'Desde 2012 com atuação no setor de TI, é Engenheiro de Software com forte experiência em desenvolvimento mobile. Já trabalhou também com desenvolvimento front-end, back-end e em manutenção de software legado. Oficialmente certificado Scrum Master (pela Scrum Alliance), é apaixonado por trabalhar com todas as correntes do Agile — Scrum, Lean, Kanban e XP. Bacharel em Ciência da Computação pela Universidade Federal do Rio Grande do Sul (UFRGS), é também blogueiro e palestrante em eventos sobre tecnologia. Nas horas vagas, é frequentador assíduo do estádio do seu time de coração, game maníaco desde os quatro anos de idade e viciado em happy hours.',
	    writerImg: 'assets/image/writers/roger-silva.png',
	    bigImageUrl: 'assets/image/books/EntregaContinuaAndroid.png',
	    middleImageUrl: 'assets/image/books/EntregaContinuaAndroid.png',
	    smallImageUrl: 'assets/image/books/EntregaContinuaAndroid.png'
    },
    {
        id: 30,
	    title: 'Iniciando com Flutter Framework',
	    upon: 'Desenvolva aplicações móveis no Dart Side!',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 173,
	    datePubli: '07/2020',
	    pricePrinted: 47.92,
	    priceEbook: 31.92,
	    pricePackage: 59.92,
	    description: 'Neste livro, Leonardo Marinho mostra quais dores o Flutter veio para curar, com a criação de aplicativos verdadeiramente performáticos, atrativos e multiplataforma. Você conhecerá desde a arquitetura de software fantástica por baixo dele e as razões pelas quais Dart foi a linguagem escolhida para programar nele, verá que tudo será organizado com Widgets e poderá aproveitá-los ao máximo. Pelo caminho, colocará em prática as principais etapas da criação de um aplicativo, como gerenciamento de dependências, requisições http, banco de dados local, testes automatizados, estilização e muito mais!',
	    writer: 'Leonardo H Marinho',
	    aboutWriter: 'Leonardo é graduado em Análise e Desenvolvimento de Sistemas e atualmente é mestrando em sistemas de informação pela Universidade Federal do Rio de Janeiro (UFRJ). Desenvolvedor Full Stack apaixonado por criar aplicativos para dispositivos móveis (Android e IOS) com tecnologias como Ionic e Flutter. Organizador da conferência OpenLabs, atualmente a maior conferência tecnológica da região serrana carioca. Nos finais de semana prepara aulas para seus cursos de programação em modalidade EaD, didática e transmissão de conhecimento são suas grandes paixões. É membro fundador da comunidade Dart Lang Brasil. Gosta de Star Wars e café.',
	    writerImg: 'assets/image/writers/leonardo-h-marinho.png',
	    bigImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png',
	    middleImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png',
	    smallImageUrl: 'assets/image/books/IniciandocomFlutterFramework.png'    
    },
    {
        id: 31,
	    title: 'React Native',
	    upon: 'Desenvolvimento de aplicativos mobile com React',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 189,
	    datePubli: '08/2021',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Bruna Escudelario e Diego Pinho vão desde os primeiros passos com React Native até o desenvolvimento de aplicações que consomem serviços na internet (APIs). No meio deste percurso, você vai aproveitar e estudar o funcionamento da biblioteca React para web, afinal, todos os conceitos trabalhados nela também são usados aqui. Você verá o que é o JSX e como criar um componente das mais diversas formas, quais são as principais dependências, o que são propriedades e estados, estilos por meio do Flexbox e CSS, navegação de telas, quais são as principais funções do ciclo de vida de um componente, como passar informações de um componente para outro, consumir serviços da internet e atualizar os componentes com as respostas, até chegar à última grande novidade do React 16, os Hooks. Este livro foi estruturado de modo que os tópicos se complementem e se tornem gradativamente mais complexos ao decorrer da leitura, mas sempre apoiados por códigos contextualizados em casos de usos reais, seguindo as boas práticas adotadas pelo mercado e pela comunidade desenvolvedora.',
	    writer: 'Bruna Escudelario',
	    aboutWriter: 'Bruna Escudelario é Desenvolvedora Web com experiência na área de front-end com as tecnologias e frameworks: HTML5, CSS3, JavaScript, Node.js, Gulp.js, entre outras. Tem bacharelado em Ciência da Computação pela Pontifícia Universidade Católica de São Paulo (PUC-SP) e é entusiasta em desenvolvimento de jogos.',
	    writerImg: 'assets/image/writers/bruna-escudelario.png',
	    bigImageUrl: 'assets/image/books/ReactNative.png',
	    middleImageUrl: 'assets/image/books/ReactNative.png',
	    smallImageUrl: 'assets/image/books/ReactNative.png'  
    },
    {
        id: 32,
	    title: 'Cordova avançado e PhoneGap',
	    upon: 'Um guia detalhado do zero à publicação',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 292,
	    datePubli: '03/2018',
	    pricePrinted: 63.92,
	    priceEbook: 23.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Diogo Machado se volta aos profissionais da área de tecnologia que já possuam uma experiência básica com Cordova e PhoneGap, mas que desejam expandir suas possibilidades e tornar suas aplicações mais robustas. Ao acompanhar a criação de um projeto completo, você verá como utilizar os principais plug-ins, integrar a plataforma Firebase, construir elementos visuais do zero usando código web e, o melhor, com todo o processo de publicação detalhado em Android e iOS.',
	    writer: 'Diogo Machado',
	    aboutWriter: 'Diogo Souza Machado, sou desenvolvedor web/mobile e desde 2010 trabalho com PHP, MySQL, JavaScript, HTML e CSS. Ao longo desses, anos adquiri experiência e maturidade na área. Estou sempre estudando, gosto de testar coisas novas, mas algumas tecnologias são minhas favoritas, como o Angular, PhoneGap/Cordova, CSS3 e HTML5. Atualmente, trabalho como Analista de Sistemas na Unimed Sul Capixaba, mas também produzo aplicativos e sistemas para outras empresas, ministro palestras, cursos e escrevo artigos no site.',
	    writerImg: 'assets/image/writers/diogo-machado.png',
	    bigImageUrl: 'assets/image/books/Cordova_Amazon.png',
	    middleImageUrl: 'assets/image/books/Cordova_Amazon.png',
	    smallImageUrl: 'assets/image/books/Cordova_Amazon.png'          
    },
    {
        id: 33,
	    title: 'Xamarin Forms',
	    upon: 'Desenvolvimento de aplicações móveis multiplataforma',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 303,
	    datePubli: '09/2020',
	    pricePrinted: 63.92,
	    priceEbook: 31.92,
	    pricePackage: 75.92,
	    description: 'Neste livro, Everton Coimbra traz, na prática, o desenvolvimento de aplicações multiplataforma com o Xamarin e Xamarin Forms, apresentando conceitos como componentes, ações, acesso a bases de dados via SQLite, mapas e muito mais. Explorando as potencialidades do Xamarin e de tecnologias afins, você acompanhará a construção de um aplicativo para diferentes dispositivos móveis a partir de uma mesma estrutura de código.',
	    writer: 'Everton Coimbra de Araújo',
	    aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
	    writerImg: 'assets/image/writers/everton-coimbra.png',
	    bigImageUrl: 'assets/image/books/XamarinForms.png',
	    middleImageUrl: 'assets/image/books/XamarinForms.png',
	    smallImageUrl: 'assets/image/books/XamarinForms.png'          
    },
    {
        id: 34,
	    title: 'Aplicações mobile híbridas com Cordova e PhoneGap',
	    upon: 'Aprenda a construir apps híbridos',
	    about: 'Multiplataforma',
	    section: 'mobile',
	    numPages: 202,
	    datePubli: '02/2016',
	    pricePrinted: 55.92,
	    priceEbook: 31.92,
	    pricePackage: 67.92,
	    description: 'Neste livro, Sérgio Lopes mostra o Cordova, a solução para Apps híbridas mais usada no mundo. Escreva um único código baseado em HTML5 e tenha Apps de verdade para iOS, Android e Windows Phone. Com projetos práticos, você vai ver Cordova desde o início até casos complexos de integração com hardware. Vai entender onde o PhoneGap se encaixa e até criar uma App com Ionic.',
	    writer: 'Sérgio Lopes',
	    aboutWriter: 'Sérgio Lopes programa para Web desde 2000, de preferência front-end. É instrutor e desenvolvedor na Caelum desde 2004 e possui bacharelado em Ciência da Computação na USP. Também é moderador do GUJ, palestrante de diversos eventos e ativo participante da comunidade. Nos últimos tempos, tem focado em dispositivos móveis e as implicações para a Web. Tem um blog pessoal onde fala muito de front-end e uma conta no Twitter.',
	    writerImg: 'assets/image/writers/sergio-lopes.png',
	    bigImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png',
	    middleImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png',
	    smallImageUrl: 'assets/image/books/Aplicacoesmobilehibridas.png'          
    }
]