import { Db } from './casaDoCodigo-db'
import { Injectable } from '@angular/core'

@Injectable ({
    providedIn: 'root'
})

export class DbService {
    retriveAll(): Db[] {
        return DbLivros
    }
}

let DbLivros: Db[] = [
    {
        id: 1,
        title: 'html5 e css3',
        upon: 'Domine a web do futuro',
        about: 'HTML e CSS',
        section: 'Front-End',
        numPages: 228,
        datePubli: '05/2012',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 67.92,
        description: 'Crie páginas elegantes de forma simples! HTML e CSS, quando bem utilizados, podem ser o sucesso de um projeto e, com os novos recursos, muito do que antes era trabalhoso agora não é mais. Aprenda as melhores técnicas para escrever seu site por meio de exemplos práticos de funcionalidades úteis do cotidiano. Construa menus, aplique efeitos, estilize elementos visuais, melhore a semântica da sua página e muito mais!',
        writer: 'Natan Souza',
        aboutWriter: 'Lucas Mazza faz parte da equipe de desenvolvedores da Plataformatec, empresa de desenvolvimento de São Paulo, especializada em Ruby on Rails. Combinando a linguagem Ruby com HTML, CSS e JavaScript, ele busca desenvolver interfaces elegantes aliado a um código de qualidade, que satisfaça usuários e desenvolvedores envolvidos. No seu tempo livre, ele é aficionado por filmes, música, tecnologia e contribui com projetos open Sousce no GitHub. Seu usuário no GitHub é lucasmazza e está no Twitter em @lucasmazza.',
        writerImg: 'assets/image/writers/lucas-mazza.png',
        bigImageUrl: 'assets/image/books/HTML5eCSS3.png',
        middleImageUrl: 'assets/image/books/HTML5eCSS3.png',
        smallImageUrl: 'assets/image/books/HTML5eCSS3.png'
    }, 
    {
        id: 2,
        title: 'css3 eficiente',
        upon: 'Técnicas e ferramentas que fazem a diferença nos seus estilos',
        about: 'HTML e CSS',
        section: 'Front-End',
        numPages: 144,
        datePubli: '06/2015',
        pricePrinted: 52.15,
        priceEbook: 23.92,
        pricePackage: 62.99,
        description: 'Quando aprendemos a trabalhar com CSS, frequentemente nos pegamos perdidos em detalhes fundamentais que não nos são explicados. Por vezes, alguns desses detalhes passam despercebidos até pelo desenvolvedor front-end mais experiente. Mas como ir além do conhecimento básico do CSS e preparar o caminho para explorar tópicos mais avançados?',
        writer: 'Tárcio Zemel',
        aboutWriter: 'Tárcio Zemel trabalha com desenvolvimento web há 15 anos e atuar nessa área é uma das coisas que mais gosta de fazer. É sócio-fundador da empresa webfatorial, na qual trabalha em projetos web para grandes marcas do mundo todo.',
        bigImageUrl: 'assets/image/books/CSS3Eficiente.png',
        writerImg: 'assets/image/writers/tarcio-zemel.png',
        middleImageUrl: 'assets/image/books/CSS3Eficiente.png',
        smallImageUrl: 'assets/image/books/CSS3Eficiente.png'
    },
    {
        id: 3,
        title: 'sass',
        upon: 'Aprendendo pré-processadores CSS',
        about: 'HTML e CSS',
        section: 'Front-End',
        numPages: 166,
        datePubli: '08/2016',
        pricePrinted: 47.92,
        priceEbook: 29.95,
        pricePackage: 59.92,
        description: 'Na última década, surgiram os chamados processadores CSS, tecnologias que buscavam suprir as deficiências que encontrávamos na utilização de CSS comum, como repetição de código, ausência de funções, a difícil manutenção entre outros fatores. Sabemos que a única linguagem de estilos que os navegadores compreendem atualmente é o bom e velho CSS, daí a necessidade de um pré-processador que receba dados de entrada e os devolva compilados em um arquivo .css, facilitando o dia a dia do desenvolvimento front-end e trazendo grandes vantagens na implementação dos estilos.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Sass.png',
        middleImageUrl: 'assets/image/books/Sass.png',
        smallImageUrl: 'assets/image/books/Sass.png'
    },
    {
        id: 4,
        title: 'bootstrap 4',
        upon: 'Conheça a biblioteca front-end mais utilizada no mundo',
        about: 'HTML e CSS',
        section: 'Front-End',
        numPages: 172,
        datePubli: '05/2018',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'Fazer um site elegante nunca foi tão fácil, mesmo para quem não sabe escrever uma linha de CSS e, muito menos, entende como harmonizar cores, balancear elementos e tipografia. O Bootstrap é, resumidamente, um grande arquivo CSS com uma excelente documentação, que possui dezenas e dezenas de componentes prontos. No começo, foi criado pelo Twitter para servir como um guia de estilos em CSS da empresa; hoje, é a biblioteca mais famosa e utilizada no mundo.',
        writer: 'Natan Souza',
        aboutWriter: 'Natan Souza é front-end designer no grupo Caelum desde 2015, e instrutor dos cursos presenciais de front-end e UX. Além disso, também produz cursos online dessas áreas para a Alura, incluindo os cursos de Sass e LESS. Começou a dar seus primeiros cliques no Photoshop ainda em 2005, o que o levaria a se interessar pela área de Design, e graduando-se bacharel em Design Digital anos mais tarde. Está focado na área de web e UX desde 2009, passando por empresas como FIAP e PMESP. Atuou como front-end e designer em toda a sua trajetória profissional. Twitter: @designernatan',
        writerImg: 'assets/image/writers/natan-souza.png',
        bigImageUrl: 'assets/image/books/Bootstrap.png',
        middleImageUrl: 'assets/image/books/Bootstrap.png',
        smallImageUrl: 'assets/image/books/Bootstrap.png'
    },
    {
        id: 5,
        title: 'ecmascript 6',
        upon: 'Entre de cabeça no futuro do JavaScript',
        about: 'Javascript',
        section: 'Front-End',
        numPages: 227,
        datePubli: '05/2018',
        pricePrinted: 55.92,
        priceEbook: 35.55,
        pricePackage: 67.92,
        description: 'Nos últimos anos, a linguagem JavaScript cresceu bastante na comunidade de desenvolvedores, tornando-se mais robusta, poderosa e sendo usada em uma infinidade de aplicações de alto nível, tanto no front-end quanto no back-end das aplicações. Ela é a tecnologia por trás de ferramentas, frameworks e bibliotecas consagradas no mercado, tais como: Angular, Ember, React, Backbone, jQuery, Grunt. A lista é enorme. Atualmente, é essencial que um profissional de TI tenha domínio desta tecnologia, tanto para aplicações web, aplicativos mobile e/ou desktop. É exatamente para isto que este livro foi escrito. Para que você seja capaz de entender todas as mudanças que vieram com o ECMAScript 6, aprimorar suas habilidades como desenvolvedor e se destacar no mercado de trabalho que hoje é tão concorrido.',
        writer: 'Diego Martins de Pinho',
        aboutWriter: 'Bacharel em Ciência da Computação pela PUC-SP e MBA em Gestão da Tecnologia da Informação pela FIAP. É aficionado não somente por tecnologia, mas também por empreendedorismo e gestão de negócios. Trabalha com desenvolvimento web desde 2013 e sempre busca tempo para continuar aprendendo e para disseminar o conhecimento.',
        writerImg: 'assets/image/writers/diego-martins.png',
        bigImageUrl: 'assets/image/books/ECMAScript6.png',
        middleImageUrl: 'assets/image/books/ECMAScript6.png',
        smallImageUrl: 'assets/image/books/ECMAScript6.png'
    },
    {
        id: 6,
        title: 'angular 11 e firebase',
        upon: 'Construindo uma aplicação integrada com a plataforma do Google',
        about: 'Javascript',
        section: 'Front-End',
        numPages: 163,
        datePubli: '03/2021',
        pricePrinted: 47.92,
        priceEbook: 33.55,
        pricePackage: 60.55,
        description: 'No desenvolvimento de aplicações web e mobile, há disponível uma quantidade expressiva de linguagens, frameworks e ferramentas. Nessa imensidão, é comum se questionar ou até ter inseguranças sobre qual o melhor caminho para a construção neste segmento. O Angular é uma plataforma que facilita a construção de aplicativos, combinando templates, injeção de dependências, tudo integrado às melhores práticas de desenvolvimento.',
        writer: 'Kheronn Khennedy Machado',
        aboutWriter: 'Kheronn Khennedy Machado é professor da rede pública estadual do Paraná. Atua na formação de professores para uso de tecnologia em sala de aula. Desenvolve desde 2007 aplicações para web e mobile, tendo recentemente focado em soluções que utilizam Javascript. Possui Mestrado em Informática pela UFPR e Graduação em Processamento de Dados pela Fatec Ourinhos.',
        writerImg: 'assets/image/writers/kheronn-khennedy.png',
        bigImageUrl: 'assets/image/books/AngularEFirebase.png',
        middleImageUrl: 'assets/image/books/AngularEFirebase.png',
        smallImageUrl: 'assets/image/books/AngularEFirebase.png'
    },
    {
        id: 7,
        title: 'guia prático de typescript',
        upon: 'Melhore suas aplicações JavaScript',
        about: 'Javascript',
        section: 'Front-End',
        numPages: 178,
        datePubli: '07/2021',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.84,
        description: 'Desenvolvido e mantido pela Microsoft, o TypeScript é um pré-processador open source de códigos JavaScript que auxilia na escrita de códigos, desde os mais simples até os mais complexos, utilizando tipagem de dados e os princípios da Orientação a Objetos para o desenvolvimento de aplicações front-end, back-end e mobile.',
        writer: 'Thiago da Silva Adriano',
        aboutWriter: 'Thiago da Silva Adriano é Microsoft (MVP) e atualmente trabalha como Engenheiro de Software. Nesses últimos anos, focou nas tecnologias criadas pela Microsoft, mas sempre esteve antenado para as novas tecnologias que estão surgindo no mercado. Em um breve resumo, é uma pessoa apaixonada pelo que faz, tem a sua profissão como hobby.',
        writerImg: 'assets/image/writers/thiago-silva.png',
        bigImageUrl: 'assets/image/books/GuiaTypescript.png',
        middleImageUrl: 'assets/image/books/GuiaTypescript.png',
        smallImageUrl: 'assets/image/books/GuiaTypescript.png'
    },
    {
        id: 8,
        title: 'vue.js',
        upon: 'construa aplicações incríveis',
        about: 'Javascript',
        section: 'Front-End',
        numPages: 174,
        datePubli: '04/2017',
        pricePrinted: 47.92,
        priceEbook: 31.92,
        pricePackage: 59.92,
        description: 'O modo como desenvolvemos código front-end mudou muito ao longo dos últimos anos. Mais do que dar as ferramentas necessárias para desenvolver, os frameworks de componentes reativos para interfaces web modernas vieram nos ajudar com padrões e reaproveitamento de código. Vue.js, ou simplesmente Vue, é uma biblioteca moderna de desenvolvimento front-end, uma lib JavaScript para componentes reativos para web. Ele ganhou muita visibilidade no mercado após ser adotado como padrão pelo Laravel, tendo a possibilidade de ser utilizado em qualquer projeto que possua front-end, independente da linguagem de programação escolhida.',
        writer: 'Caio Incau',
        aboutWriter: 'Caio Incau estudou Sistemas de Informação e trabalha com desenvolvimento de software na Caelum desde seus 18 anos. Durante sua estadia no mercado de TI, teve a oportunidade de trabalhar com Java, Ruby, JavaScript e Objective-C.',
        writerImg: 'assets/image/writers/caio-incau.png',
        bigImageUrl: 'assets/image/books/VueJS.png',
        middleImageUrl: 'assets/image/books/VueJS.png',
        smallImageUrl: 'assets/image/books/VueJS.png'
    },
    {
        id: 9,
        title: 'acessibilidade na web',
        upon: 'Boas práticas para construir sites e aplicações acessíveis',
        about: 'Outros',
        section: 'Front-End',
        numPages: 246,
        datePubli: '04/2020',
        pricePrinted: 55.92,
        priceEbook: 31.92,
        pricePackage: 71.92,
        description: 'Acessibilidade na Web consiste na eliminação de barreiras de acesso em páginas e aplicações digitais para que pessoas com deficiência tenham autonomia na rede. Na verdade, acessibilidade na web beneficia todas as pessoas. Em algum momento da vida todos podem precisar de acessibilidade, seja devido a uma limitação temporária ou permanente. Quando não levamos em consideração o acesso de pessoas com deficiência, estamos tirando o direito de uma pessoa de navegar, interagir ou consumir produtos e serviços na rede. Empatia é o fator principal para que as aplicações que desenvolvemos sejam inclusivas.',
        writer: 'Reinaldo Ferraz',
        aboutWriter: 'Formado em desenho e computação gráfica e pós-graduado em design de hipermídia pela Universidade Anhembi Morumbi em São Paulo. Trabalha com desenvolvimento web desde 1998. Coordena as iniciativas de acessibilidade na Web do NIC.br e projetos relacionados a Open Web Platform, Digital Publishing e Web das Coisas. Representante do NIC.br em grupos de trabalho do W3C internacional em Acessibilidade na Web, Digital Publishing e Web das Coisas. Apaixonado por acessibilidade, usabilidade, padrões web, HTML, CSS e café sem açúcar.',
        writerImg: 'assets/image/writers/reinaldo-ferraz.png',
        bigImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        middleImageUrl: 'assets/image/books/Acessibilidade-na-Web.png',
        smallImageUrl: 'assets/image/books/Acessibilidade-na-Web.png'
    },
    {
        id: 10,
        title: 'progressive web apps',
        upon: 'Construa aplicações progressivas com React',
        about: 'Outros',
        section: 'Front-End',
        numPages: 443,
        datePubli: '04/2018',
        pricePrinted: 71.92,
        priceEbook: 31.92,
        pricePackage: 83.92,
        description: 'PWA é um acrônimo para Progressive Web Apps, ou Aplicações Web Progressivas. Com o passar dos dias, mais e mais sistemas mobile e navegadores suportam os requisitos PWA, com uma expectativa real de que a Progressive Enhancement, ou melhoria progressiva, deixe de apenas pertencer às boas práticas de desenvolvimento web e passe a ser norma. Desenvolver com melhoria progressiva é um paradigma em que a aplicação deverá estar disponível para todos, sejam usuários de microcomputadores ou smartphones, com browsers atualizados ou obsoletos, com conexão à internet ou não, propiciando uma experiência de acesso contínuo sem nenhum tipo de restrição tecnológica.',
        writer: 'Guilherme Pontes',
        aboutWriter: 'Um profissional de TI, que adora TI, principalmente quando se trata de minúcias relacionadas a Linux, Node.JS, Python, MySQL, MongoDB, apps mobile ou progressivas, e muito JavaScript. http://lgapontes.com/',
        writerImg: 'assets/image/writers/guilherme-pontes.png',
        bigImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        middleImageUrl: 'assets/image/books/ProgressiveWebApps.png',
        smallImageUrl: 'assets/image/books/ProgressiveWebApps.png'
    },
    {
        id: 11,
        title: 'introdução à web semântica',
        upon: 'A inteligência da informação',
        about: 'Outros',
        section: 'Front-End',
        numPages: 170,
        datePubli: '09/2012',
        pricePrinted: 47.92,
        priceEbook: 23.92,
        pricePackage: 59.92,
        description: 'Por que precisamos da Web Semântica? A Web de hoje não é suficiente? Estamos caminhando para uma Web com dados cada vez mais relacionados e abertos. A Web Semântica é uma extensão da nossa web atual, em que nós não vamos apenas ler e produzir conteúdo, mas usar as máquinas para relacionar e reutilizar essas informações da melhor maneira possível. Ela se baseia na ideia de que o conteúdo deve ter uma descrição digital, padronizada por vocabulários, que provê meios para as máquinas entenderem do que aquilo se trata, de modo que os computadores possam interpretar, gerar e distribuir conteúdo útil, de acordo com as necessidades dos usuários.',
        writer: 'Diego Eis',
        aboutWriter: 'Diego Eis é apaixonado e sempre trabalhou com internet. Em 2003, fundou o Tableless, onde escreve com vários outros autores sobre desenvolvimento web e front-end. Já palestrou em vários eventos nacionais de tecnologia, faculdades e empresas por todo o país, passou seis anos de sua carreira profissional dirigindo a própria empresa, fazendo projetos para companhias como Globo.com, Itaú, Nokia, Samsung e outras. É autor do livro Guia Front-End, destinado aos iniciantes da área. Atualmente, é gestor de produtos na Easynvest.',
        writerImg: 'assets/image/writers/diego-eis.png',
        bigImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        middleImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png',
        smallImageUrl: 'assets/image/books/IntroducaoaWebSemantica.png'
    },
    {
        id: 12,
        title: 'aprofundando em flutter',
        upon: 'Desenvolva aplicações Dart com Widgets',
        about: 'Outros',
        section: 'Front-End',
        numPages: 319,
        datePubli: '06/2021',
        pricePrinted: 63.92,
        priceEbook: 31.92,
        pricePackage: 75.92,
        description: 'Flutter é um framework do Google que tem conquistado o coração de muitas pessoas no desenvolvimento de aplicativos cross-platform, tanto para dispositivos móveis, como com versões estáveis para desenvolvimento web, desktop e PWA. Sua estrutura baseada em widgets, que são componentes visuais ou não, com propriedades e eventos customizáveis através da linguagem Dart, abre um leque infinito de possibilidades para criar aplicações completas. Se você já conhece Flutter e quer dar o próximo passo nessa relação, este é o caminho.',
        writer: 'Everton Coimbra de Araújo',
        aboutWriter: 'Everton Coimbra de Araújo atua na área de treinamento e desenvolvimento. É tecnólogo em processamento de dados pelo Centro de Ensino superior de Foz do Iguaçu, possui mestrado em Ciência da Computação pela UFSC e doutorado pela UNIOESTE em Engenharia Agrícola. É professor da Universidade Tecnológica Federal do Paraná (UTFPR), possui experiência na área de Ciência da Computação, com ênfase em Análise e Desenvolvimento de Sistemas, atuando principalmente nos seguintes temas: Desenvolvimento Web com Java e .NET, Persistência de Objetos e desenvolvimento de aplicativos para dispositivos móveis.',
        writerImg: 'assets/image/writers/everton-coimbra-de-araujo.png',
        bigImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        middleImageUrl: 'assets/image/books/Aprofundandoemflutter.png',
        smallImageUrl: 'assets/image/books/Aprofundandoemflutter.png'
    }
]